"""Phase C12: managed-skills registry + --prune-orphan-skills.

Tests cover:
- Registry is written on each `configure` run (~/.dotpanel/managed-skills.json)
- Registry schema (skills + harnesses + written_at)
- --prune-orphan-skills removes banner-marked dirs not in registry
- Prune skips dirs without dotpanel banner (user-created skills protected)
- Dry-run mode prints WOULD-PRUNE without deleting
- C12 dot -> sync rename: cli.py registries renamed; render produces sync wrapper
"""
from __future__ import annotations

import contextlib
import io
import json
import os
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest import mock

from dotpanel.cli import (
    CANONICAL_SKILL_FILES,
    SKILL_DESCRIPTIONS,
    SKILL_TITLES,
    USER_FACING_SKILLS,
    DotpanelPaths,
    _current_managed_skill_names,
    _managed_skills_registry_path,
    _write_managed_skills_registry,
    skill_wrapper_body,
)


GENERATED_BANNER = "<!-- Generated by dotpanel; do not edit directly. -->"


class CLIRegistryRenameTests(unittest.TestCase):
    """C12: ensure /dot was renamed to /sync everywhere."""

    def test_sync_in_user_facing_skills(self) -> None:
        self.assertIn("sync", USER_FACING_SKILLS)
        self.assertNotIn("dot", USER_FACING_SKILLS)

    def test_sync_canonical_file_unchanged(self) -> None:
        # The skill name was renamed; the source body file stays config-sync.md.
        self.assertEqual(CANONICAL_SKILL_FILES["sync"], "config-sync.md")
        self.assertNotIn("dot", CANONICAL_SKILL_FILES)

    def test_sync_in_skill_titles_and_descriptions(self) -> None:
        self.assertIn("sync", SKILL_TITLES)
        self.assertIn("sync", SKILL_DESCRIPTIONS)
        self.assertNotIn("dot", SKILL_TITLES)
        self.assertNotIn("dot", SKILL_DESCRIPTIONS)


class WrapperRendersSyncTests(unittest.TestCase):
    def test_skill_wrapper_body_for_sync(self) -> None:
        body = skill_wrapper_body("sync", "claude", "/tmp/dotpanel-root")
        self.assertIn("name: sync", body)
        self.assertIn("config-sync.md", body)
        self.assertNotIn("name: dot\n", body)


class RegistryWriteTests(unittest.TestCase):
    def test_write_registry_schema(self) -> None:
        with TemporaryDirectory() as t:
            home = Path(t)
            _write_managed_skills_registry(
                home, ["plan", "review", "sync"], ["claude", "codex"], dry_run=False
            )
            target = _managed_skills_registry_path(home)
            self.assertTrue(target.exists())
            payload = json.loads(target.read_text())
            self.assertEqual(payload["schema_version"], "1")
            self.assertEqual(payload["skills"], ["plan", "review", "sync"])
            self.assertEqual(payload["harnesses"], ["claude", "codex"])
            self.assertIn("written_at", payload)

    def test_dry_run_does_not_write(self) -> None:
        with TemporaryDirectory() as t:
            home = Path(t)
            _write_managed_skills_registry(home, ["plan"], ["claude"], dry_run=True)
            self.assertFalse(_managed_skills_registry_path(home).exists())


class CurrentManagedNamesTests(unittest.TestCase):
    """_current_managed_skill_names unions public + substrate skills."""

    def setUp(self) -> None:
        self._tmp = TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.tmp = Path(self._tmp.name)

    def test_includes_public_skills(self) -> None:
        # Without a substrate, the set is just USER_FACING_SKILLS.
        # We point DOTPANEL_SUBSTRATE at an empty dir to skip env discovery.
        empty_substrate = self.tmp / "empty_substrate"
        empty_substrate.mkdir()
        # Don't create .dotpanel.toml so find_substrate raises and falls back.
        with mock.patch.dict(os.environ, {}, clear=False):
            os.environ.pop("DOTPANEL_SUBSTRATE", None)
            # Force the home discovery to a path without a config too.
            with mock.patch(
                "dotpanel.cli._try_find_substrate", return_value=None,
            ):
                names = _current_managed_skill_names(
                    DotpanelPaths(root=Path("/tmp"), home=self.tmp)
                )
        for s in USER_FACING_SKILLS:
            self.assertIn(s, names)


if __name__ == "__main__":
    unittest.main()
