"""v5 tests for dotpanel CLI.

Each test uses a sandboxed DotpanelPaths constructed against a tmp directory.
Some tests require actual file structure (protocol/harness/templates) so we
copy or stub the minimum needed.
"""
from __future__ import annotations

import tarfile
import unittest
import zipfile
from contextlib import redirect_stdout, redirect_stderr
from io import StringIO
from pathlib import Path
from tempfile import TemporaryDirectory

from dotpanel import __version__
from dotpanel.cli import (
    GENERATED_BANNER,
    DOTPANEL_MANAGED_JSON,
    DotpanelPaths,
    USER_FACING_SKILLS,
    cmd_audit,
    cmd_audit_dist,
    cmd_configure,
    cmd_root,
    dotpanel_root,
    has_dotpanel_banner,
    _excluded_path,
    render_text,
    skill_wrapper_body,
)


def _seed_dotpanel_tree(root: Path, persona_root: Path | None = None) -> None:
    """Create minimum file tree for cmd_doctor/cmd_configure to work in a tmp root."""
    (root / "protocol" / "skills").mkdir(parents=True)
    (root / "protocol" / "rules").mkdir(parents=True)
    (root / "protocol" / "reference").mkdir(parents=True)
    (root / "protocol" / "workspace.md").write_text("# Universal protocol\n")

    (root / "harness" / "claude" / "templates").mkdir(parents=True)
    (root / "harness" / "claude" / "templates" / "CLAUDE.md").write_text(
        "<!-- Generated by dotpanel; do not edit directly. -->\nRead {{DOTPANEL_ROOT}}/persona/voice.md\nthen {{DOTPANEL_ROOT}}/protocol/workspace.md\n"
    )
    (root / "harness" / "claude" / "templates" / "settings.json").write_text(
        '{"language": "english"}\n'
    )
    (root / "harness" / "codex" / "templates").mkdir(parents=True)
    (root / "harness" / "codex" / "templates" / "AGENTS.md").write_text(
        "<!-- Generated by dotpanel; do not edit directly. -->\nRead {{DOTPANEL_ROOT}}/persona/voice.md\nthen {{DOTPANEL_ROOT}}/protocol/workspace.md\n"
    )
    (root / "harness" / "codex" / "templates" / "config.toml").write_text(
        "# Generated by dotpanel; do not edit directly.\nmodel = \"placeholder\"\n"
    )
    (root / "harness" / "kimi" / "templates").mkdir(parents=True)
    (root / "harness" / "kimi" / "templates" / "AGENTS.md").write_text(
        "<!-- Generated by dotpanel; do not edit directly. -->\nRead {{DOTPANEL_ROOT}}/persona/voice.md\nthen {{DOTPANEL_ROOT}}/protocol/workspace.md\n"
    )

    (root / "pyproject.toml").write_text("# placeholder for doctor\n")

    # Set up canonical skill files (referenced by skill_wrapper_body / configure)
    for filename in ("plan-discussion.md", "code-review.md", "ship-pipeline.md",
                     "session-wrap.md", "config-sync.md",
                     "tool-lifecycle.md", "curriculum-bridge.md", "design-audit.md"):
        (root / "protocol" / "skills" / filename).write_text(f"# {filename}\n")

    # Persona symlink (simulating dotpanel init result) — flat persona, no slug
    if persona_root:
        persona_root.mkdir(parents=True, exist_ok=True)
        (persona_root / "voice.md").write_text("# voice\n")
        (persona_root / "identity.yaml").write_text(
            "name:\n  chinese: \"testop\"\nhandle: testop\nemail: test@example.com\n"
        )
        (root / "persona").symlink_to(persona_root)


# ---------------------------------------------------------------------------
# Module-level constants and pure functions
# ---------------------------------------------------------------------------

class ConstantsTests(unittest.TestCase):
    def test_version_is_semver(self) -> None:
        self.assertRegex(__version__, r"^\d+\.\d+\.\d+(?:[-+\w.]*)?$")

    def test_user_facing_skills_have_canonical_files(self) -> None:
        from dotpanel.cli import CANONICAL_SKILL_FILES, SKILL_TITLES, SKILL_DESCRIPTIONS
        for skill in USER_FACING_SKILLS:
            self.assertIn(skill, CANONICAL_SKILL_FILES)
            self.assertIn(skill, SKILL_TITLES)
            self.assertIn(skill, SKILL_DESCRIPTIONS)

    def test_managed_json_list_is_short(self) -> None:
        # Per ADR-3 "doctor warns if list exceeds 5 entries" trigger threshold
        self.assertLessEqual(len(DOTPANEL_MANAGED_JSON), 5)

    def test_d7_curriculum_bridge_relocated_to_substrate(self) -> None:
        # D7: curriculum-bridge moved to substrate skills/ — public set drops it.
        self.assertNotIn("curriculum-bridge", USER_FACING_SKILLS)

    def test_d7_teamleader_relocated_to_substrate(self) -> None:
        # D7: teamleader moved to substrate skills/ — public set drops it.
        self.assertNotIn("teamleader", USER_FACING_SKILLS)

    def test_c12_slash_sync_replaces_slash_dot(self) -> None:
        # C12: /dot renamed to /sync.
        self.assertIn("sync", USER_FACING_SKILLS)
        self.assertNotIn("dot", USER_FACING_SKILLS)

    def test_c12_sync_canonical_filename_unchanged(self) -> None:
        # C12: skill renames to "sync" but canonical body remains config-sync.md.
        from dotpanel.cli import CANONICAL_SKILL_FILES
        self.assertEqual(CANONICAL_SKILL_FILES["sync"], "config-sync.md")


class RenderTextTests(unittest.TestCase):
    def test_renders_dotpanel_root(self) -> None:
        out = render_text("see {{DOTPANEL_ROOT}}/persona/voice.md", "/foo")
        self.assertEqual(out, "see /foo/persona/voice.md")

    def test_renders_sync_command_placeholder(self) -> None:
        out = render_text("Run {{SYNC_COMMAND}} push", "/foo")
        self.assertEqual(out, "Run dotpanel sync push")

    def test_renders_sync_command_custom_override(self) -> None:
        out = render_text("Run {{SYNC_COMMAND}}", "/foo", sync_command="my-sync run")
        self.assertEqual(out, "Run my-sync run")

    def test_no_placeholders_passes_through(self) -> None:
        self.assertEqual(render_text("plain text", "/foo"), "plain text")


class BannerTests(unittest.TestCase):
    def test_first_line_banner_detected(self) -> None:
        with TemporaryDirectory() as t:
            f = Path(t) / "x.md"
            f.write_text("Generated by dotpanel test\nbody\n")
            self.assertTrue(has_dotpanel_banner(f))

    def test_banner_after_yaml_frontmatter_detected(self) -> None:
        # Critical case from round-3 N1: SKILL.md wrappers have YAML frontmatter
        # ABOVE the banner. has_dotpanel_banner must scan first 10 lines.
        with TemporaryDirectory() as t:
            f = Path(t) / "x.md"
            f.write_text("---\nname: foo\ndescription: bar\n---\n\nGenerated by dotpanel\nbody\n")
            self.assertTrue(has_dotpanel_banner(f))

    def test_banner_beyond_scan_window_not_detected(self) -> None:
        with TemporaryDirectory() as t:
            f = Path(t) / "x.md"
            # 12 lines of frontmatter then banner — beyond default BANNER_SCAN_LINES=10
            lines = ["lorem ipsum"] * 12 + ["Generated by dotpanel"]
            f.write_text("\n".join(lines))
            self.assertFalse(has_dotpanel_banner(f))


# ---------------------------------------------------------------------------
# cmd_root / cmd_version (via main argparse)
# ---------------------------------------------------------------------------

class RootCommandTests(unittest.TestCase):
    def test_cmd_root_prints_install_root(self) -> None:
        # cmd_root calls dotpanel_root() which uses real install location
        buf = StringIO()
        with redirect_stdout(buf):
            self.assertEqual(cmd_root(), 0)
        out = buf.getvalue().strip()
        self.assertTrue(Path(out).is_dir())
        self.assertTrue((Path(out) / "pyproject.toml").exists())


# ---------------------------------------------------------------------------
# cmd_audit
# ---------------------------------------------------------------------------

class AuditTests(unittest.TestCase):
    def test_audit_passes_on_clean_tree(self) -> None:
        with TemporaryDirectory() as t:
            root = Path(t)
            persona = root / "p"
            _seed_dotpanel_tree(root, persona)
            paths = DotpanelPaths(root=root, home=Path(t))
            with redirect_stdout(StringIO()):
                self.assertEqual(cmd_audit(paths), 0)



# ---------------------------------------------------------------------------
# cmd_audit_dist
# ---------------------------------------------------------------------------

class AuditDistTests(unittest.TestCase):
    def test_no_dist_dir_passes(self) -> None:
        with TemporaryDirectory() as t:
            paths = DotpanelPaths(root=Path(t), home=Path(t))
            with redirect_stdout(StringIO()):
                self.assertEqual(cmd_audit_dist(paths), 0)

    def test_dist_with_persona_member_in_whl_fails(self) -> None:
        with TemporaryDirectory() as t:
            root = Path(t)
            (root / "dist").mkdir()
            whl = root / "dist" / "dotpanel-x-py3-none-any.whl"
            with zipfile.ZipFile(whl, "w") as zf:
                zf.writestr("dotpanel/__init__.py", "x = 1\n")
                zf.writestr("persona/leak.md", "leaked!")
            paths = DotpanelPaths(root=root, home=root)
            with redirect_stdout(StringIO()), redirect_stderr(StringIO()):
                self.assertEqual(cmd_audit_dist(paths), 2)

    def test_dist_with_persona_member_in_targz_fails(self) -> None:
        with TemporaryDirectory() as t:
            root = Path(t)
            (root / "dist").mkdir()
            tgz = root / "dist" / "dotpanel-x.tar.gz"
            with tarfile.open(tgz, "w:gz") as tf:
                # Add a clean file
                clean_path = root / "ok.md"
                clean_path.write_text("ok")
                tf.add(clean_path, arcname="dotpanel-x/ok.md")
                # Add persona leak
                leak_path = root / "leak.md"
                leak_path.write_text("leak")
                tf.add(leak_path, arcname="dotpanel-x/persona/leak.md")
            paths = DotpanelPaths(root=root, home=root)
            with redirect_stdout(StringIO()), redirect_stderr(StringIO()):
                self.assertEqual(cmd_audit_dist(paths), 2)

    def test_dist_clean_passes(self) -> None:
        with TemporaryDirectory() as t:
            root = Path(t)
            (root / "dist").mkdir()
            whl = root / "dist" / "dotpanel-x-py3-none-any.whl"
            with zipfile.ZipFile(whl, "w") as zf:
                zf.writestr("dotpanel/__init__.py", "x = 1\n")
                zf.writestr("dotpanel/cli.py", "y = 2\n")
            paths = DotpanelPaths(root=root, home=root)
            with redirect_stdout(StringIO()):
                self.assertEqual(cmd_audit_dist(paths), 0)


# ---------------------------------------------------------------------------
# Skill wrapper body
# ---------------------------------------------------------------------------

class SkillWrapperTests(unittest.TestCase):
    def test_skill_wrapper_renders_absolute_paths(self) -> None:
        body = skill_wrapper_body("plan", "claude", "/install/dotpanel")
        self.assertIn("/install/dotpanel/protocol/skills/plan-discussion.md", body)
        self.assertNotIn("{{DOTPANEL_ROOT}}", body)
        self.assertIn(GENERATED_BANNER, body)

    def test_skill_wrapper_for_codex_uses_codex_invocation(self) -> None:
        body = skill_wrapper_body("review", "codex", "/install/dotpanel")
        self.assertIn("$review", body)
        self.assertIn("codex skill", body)


# ---------------------------------------------------------------------------
# Configure output
# ---------------------------------------------------------------------------

class ConfigureTests(unittest.TestCase):
    def test_configure_all_renders_kimi_startup_adapter(self) -> None:
        with TemporaryDirectory() as t:
            root = dotpanel_root()
            home = Path(t) / "home"
            output = Path(t) / "render"
            home.mkdir()
            paths = DotpanelPaths(root=root, home=home)
            with redirect_stdout(StringIO()):
                self.assertEqual(cmd_configure(paths, "all", False, False, False, output), 0)
            kimi_agents = output / "kimi" / "AGENTS.md"
            self.assertTrue(kimi_agents.exists())
            content = kimi_agents.read_text()
            self.assertIn(f"{root}/persona/voice.md", content)
            self.assertIn(f"{root}/protocol/workspace.md", content)
            self.assertIn(GENERATED_BANNER, content)

    def test_configure_codex_renders_env_key_profiles(self) -> None:
        with TemporaryDirectory() as t:
            root = dotpanel_root()
            home = Path(t) / "home"
            output = Path(t) / "render"
            home.mkdir()
            paths = DotpanelPaths(root=root, home=home)
            with redirect_stdout(StringIO()):
                self.assertEqual(cmd_configure(paths, "codex", False, False, False, output), 0)
            config = output / "codex" / "config.toml"
            self.assertTrue(config.exists())
            content = config.read_text()
            self.assertIn('model_provider = "openai"', content)
            self.assertIn("[profiles.andy]", content)
            self.assertIn('model_provider = "andyfeng"', content)
            self.assertIn("[profiles.let]", content)
            self.assertIn('model_provider = "letaicode"', content)
            self.assertIn('env_key = "ANDYFENG_CODEX_KEY"', content)
            self.assertIn('env_key = "LETAICODE_CODEX_KEY"', content)
            self.assertNotIn("api_key =", content)

    def test_configure_codex_renders_default_permission_rules(self) -> None:
        with TemporaryDirectory() as t:
            root = dotpanel_root()
            home = Path(t) / "home"
            output = Path(t) / "render"
            home.mkdir()
            paths = DotpanelPaths(root=root, home=home)
            with redirect_stdout(StringIO()):
                self.assertEqual(cmd_configure(paths, "codex", False, False, False, output), 0)
            rules = output / "codex" / "rules" / "default.rules"
            self.assertTrue(rules.exists())
            content = rules.read_text()
            self.assertIn("Generated by dotpanel", content)
            self.assertIn('prefix_rule(pattern=["git"], decision="allow")', content)
            self.assertIn('prefix_rule(pattern=["python3", "-m", "unittest"], decision="allow")', content)

    def test_codex_only_default_rules_escape_excluded_rules_dir(self) -> None:
        self.assertFalse(_excluded_path("rules/default.rules", "codex"))
        self.assertTrue(_excluded_path("rules/custom.rules", "codex"))


if __name__ == "__main__":
    unittest.main()
