"""dotpanel — Personal Agent Workspace control plane (v5).

Public protocol + private persona + project layer + substrate self-description.
See `docs/design/2026-05-11-dotpanel-control-plane.md`.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
import shutil
import sys
import tarfile
import tempfile
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

from . import __version__
from .config import SubstrateConfig, SubstrateNotFound, find_substrate
from .context import build_context_parser, cmd_context
from .install import build_install_parser, dispatch_install
from .leaks import build_leaks_parser, cmd_leaks
from .secrets import build_secrets_parser, dispatch_secrets
from .ssh import build_ssh_parser, dispatch_ssh
from .sync import build_sync_parser, dispatch_sync


# ---------------------------------------------------------------------------
# Constants and registries
# ---------------------------------------------------------------------------

# Public skills shipped by dotpanel itself. v5 (D7) removes curriculum-bridge
# and teamleader (operator-opinion; relocated to substrate skills/) and
# (C12) renames dot → sync.
USER_FACING_SKILLS = (
    "plan",
    "review",
    "ship",
    "sync",
    "tool",
    "wrap",
)

# skill-name → canonical body filename inside protocol/skills/
CANONICAL_SKILL_FILES = {
    "plan": "plan-discussion.md",
    "review": "code-review.md",
    "ship": "ship-pipeline.md",
    "sync": "config-sync.md",
    "tool": "tool-lifecycle.md",
    "wrap": "session-wrap.md",
}

SKILL_TITLES = {
    "plan": "Plan - Structured Planning",
    "review": "Review - Code Or Design Audit",
    "ship": "Ship - Delivery Pipeline",
    "sync": "Sync - Config Sync",
    "tool": "Tool - Tool Lifecycle",
    "wrap": "Wrap - Session Close",
}

SKILL_DESCRIPTIONS = {
    "plan": (
        "Use when the user asks for structured planning for a non-trivial change, "
        "architecture choice, refactor, or new tool."
    ),
    "review": (
        "Use when the user requests code review, plan review, design review, "
        "or a UI design audit with --ui."
    ),
    "ship": (
        "Use when the user asks to run the delivery workflow: review, test, "
        "commit, push, deploy, and verify."
    ),
    "sync": (
        "Use when the user asks to sync, push, pull, or diff the operator's "
        "substrate or dotpanel."
    ),
    "tool": "Use when the user asks to try, archive, drop, delete, or evaluate tools.",
    "wrap": (
        "Use when ending a session, asked to wrap up current work, "
        "or asked to write durable handoff state."
    ),
}

GENERATED_BANNER = "<!-- Generated by dotpanel; do not edit directly. -->"
BANNER_SCAN_LINES = 10  # Banner detection scans first N lines (accommodates YAML frontmatter)

# JSON files dotpanel manages by path-list convention (no in-file banner possible).
DOTPANEL_MANAGED_JSON = [
    "~/.claude/settings.json",
]

# Set of valid placeholders in template files (EC-7). render_text WARNs on
# unknown {{...}} tokens.
KNOWN_PLACEHOLDERS = frozenset({"DOTPANEL_ROOT", "SYNC_COMMAND"})

# Paths configure NEVER writes to (per ADR-3 Don't-touch list)
CLAUDE_EXCLUDED = (
    "sessions", "history.jsonl", "projects", "debug", "cache", "backups",
    "file-history", "ide", "paste-cache", "plugins", "session-env",
    "shell-snapshots", "tasks", ".credentials.json", ".git", ".gitignore",
)
CODEX_EXCLUDED = (
    "sessions", "history.jsonl", "log", "archived_sessions", "shell_snapshots",
    "vendor_imports", "scheduled_tasks.lock", "plugins", "rules", "memories",
    "skills", ".personality_migration", ".tmp", "tmp", "installation_id",
    "version.json",
)
CODEX_EXCLUDED_GLOBS = ("*.sqlite", "*.sqlite-shm", "*.sqlite-wal", "*.sqlite-journal")
KIMI_EXCLUDED = (
    "sessions", "logs", "credentials", "user-history", "bin", "config.toml", "device_id",
    "kimi.json", "latest_version.txt",
)

PROTOCOL_AUDIT_PATHS = ("protocol/skills", "protocol/rules", "protocol/workspace.md", "protocol/reference")
AUDIT_ALLOW_LINE = "audit-allow: identity-context"
AUDIT_ALLOW_FILE = "audit-allow-file: identity-context"

# ---------------------------------------------------------------------------
# Root resolution
# ---------------------------------------------------------------------------

def dotpanel_root() -> Path:
    """Absolute path to dotpanel repository root.

    With `dotpanel/dotpanel/cli.py`, `parents[1]` returns the repo root in
    editable installs. Wheel installs must include protocol/, harness/, tools/
    as package data (verified by `dotpanel doctor`).
    """
    return Path(__file__).resolve().parents[1]


def persona_dir(root: Path | None = None) -> Path:
    """Path to the (flat) persona directory.

    Per the post-slug architecture, persona is a single directory under
    `<dotpanel-root>/persona/` (a gitignored symlink to the operator's private
    persona repo). There is no `<slug>/` indirection.
    """
    root = root or dotpanel_root()
    return root / "persona"


# ---------------------------------------------------------------------------
# Path containers
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class DotpanelPaths:
    root: Path
    home: Path

    @classmethod
    def default(cls) -> "DotpanelPaths":
        return cls(root=dotpanel_root(), home=Path(os.environ.get("HOME", "~")).expanduser())

    @property
    def protocol(self) -> Path:
        return self.root / "protocol"

    @property
    def harness(self) -> Path:
        return self.root / "harness"

    @property
    def claude_templates(self) -> Path:
        return self.harness / "claude" / "templates"

    @property
    def codex_templates(self) -> Path:
        return self.harness / "codex" / "templates"

    @property
    def kimi_templates(self) -> Path:
        return self.harness / "kimi" / "templates"

    @property
    def claude_home(self) -> Path:
        return self.home / ".claude"

    @property
    def codex_home(self) -> Path:
        return self.home / ".codex"

    @property
    def agents_home(self) -> Path:
        return self.home / ".agents"

    @property
    def kimi_home(self) -> Path:
        return self.home / ".kimi"

    def output_root(self, harness: str, override: Path | None = None) -> Path:
        if override:
            return override / harness
        if harness == "claude":
            return self.claude_home
        if harness == "codex":
            return self.codex_home
        if harness == "kimi":
            return self.kimi_home
        raise ValueError(f"unknown harness: {harness}")

    def skills_root(self, harness: str, override: Path | None = None) -> Path | None:
        if harness == "claude":
            return self.output_root("claude", override) / "skills"
        if harness == "codex":
            if override:
                return override / "agents" / "skills"
            return self.agents_home / "skills"
        if harness == "kimi":
            return None
        raise ValueError(f"unknown harness: {harness}")


# v4 alias retained for transitional callers; remove in 0.4.0.
HpanelPaths = DotpanelPaths


# ---------------------------------------------------------------------------
# Template rendering
# ---------------------------------------------------------------------------

def render_text(text: str, dotpanel_root_str: str, sync_command: str = "dotpanel sync") -> str:
    """Render template placeholders.

    Substitutes {{DOTPANEL_ROOT}} and {{SYNC_COMMAND}} (EC-7). Unknown
    {{...}} tokens emit a warning to stderr (does not error).
    """
    for match in re.finditer(r"\{\{([A-Z_][A-Z0-9_]*)\}\}", text):
        token = match.group(1)
        if token not in KNOWN_PLACEHOLDERS:
            print(f"WARN  unknown template placeholder: {{{{{token}}}}}", file=sys.stderr)
    out = text.replace("{{DOTPANEL_ROOT}}", dotpanel_root_str)
    out = out.replace("{{SYNC_COMMAND}}", sync_command)
    return out


def render_file(template_path: Path, output_path: Path, dotpanel_root_str: str,
                dry_run: bool = False, sync_command: str = "dotpanel sync") -> str:
    """Render a template file. Returns 'wrote', 'noop', or 'would'."""
    rendered = render_text(template_path.read_text(encoding="utf-8"), dotpanel_root_str, sync_command)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == rendered:
        return "noop"
    if dry_run:
        return "would"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    _write_atomic(output_path, rendered)
    return "wrote"


def _write_atomic(path: Path, content: str, *, executable: bool = False) -> None:
    """Per-file transactional write: render to temp file in same dir, then atomic rename.

    Pass `executable=True` to set mode 0o755 after the write (for shebang scripts
    like harness statusline templates that need the executable bit preserved).
    Without it, mkstemp's default 0o600 sticks — which is right for config files
    but wrong for scripts invoked by external harness clients.
    """
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.replace(tmp, path)
        if executable:
            os.chmod(path, 0o755)
    except Exception:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


# ---------------------------------------------------------------------------
# Banner detection
# ---------------------------------------------------------------------------

def has_dotpanel_banner(path: Path) -> bool:
    """Banner detection: scans first BANNER_SCAN_LINES lines.

    Accommodates YAML frontmatter (which appears before the banner in skill wrappers).
    """
    if not path.is_file():
        return False
    try:
        with path.open(encoding="utf-8", errors="replace") as fh:
            for _ in range(BANNER_SCAN_LINES):
                line = fh.readline()
                if not line:
                    return False
                if "Generated by dotpanel" in line:
                    return True
    except OSError:
        return False
    return False


def is_managed_json(path: Path, home: Path) -> bool:
    abs_path = str(path.resolve())
    for entry in DOTPANEL_MANAGED_JSON:
        managed = Path(entry.replace("~", str(home))).resolve()
        if Path(abs_path) == managed:
            return True
    return False


# ---------------------------------------------------------------------------
# Skill wrapper generation (template-free; rendered programmatically)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SubstrateSkill:
    """A skill discovered from <substrate>/skills/*.md.

    Frontmatter-driven: name + description + supported_harnesses come from the
    file's YAML front matter. Substrate skills override public skills of the
    same name (filename collision = substrate wins, per D7).
    """

    name: str
    body_path: Path
    description: str
    supported_harnesses: tuple[str, ...]


def _parse_skill_frontmatter(path: Path) -> dict[str, Any] | None:
    """Parse the YAML frontmatter of a skill file.

    Returns the parsed dict, or None on malformed/missing frontmatter.
    Emits a WARN (not FAIL) on parse errors per D7 spec — matches Python's
    import-warning model: a broken substrate file should not block configure.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"WARN  could not read skill {path}: {exc}", file=sys.stderr)
        return None
    if not text.startswith("---\n"):
        print(f"WARN  skill {path.name} lacks YAML frontmatter; skipping",
              file=sys.stderr)
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        print(f"WARN  skill {path.name} has unterminated frontmatter; skipping",
              file=sys.stderr)
        return None
    fm_text = text[4:end]
    try:
        # Prefer pyyaml when available — handles complex multiline strings.
        import yaml  # type: ignore[import-not-found]
        data = yaml.safe_load(fm_text)
        if not isinstance(data, dict):
            print(f"WARN  skill {path.name} frontmatter is not a YAML map; skipping",
                  file=sys.stderr)
            return None
        return data
    except ImportError:
        # Minimal fallback: parse top-level `key: value` lines. Sufficient for
        # the documented schema (name, description, supported_harnesses).
        return _minimal_frontmatter_fallback(fm_text, path.name)
    except Exception as exc:
        print(f"WARN  skill {path.name} frontmatter parse failed: {exc}; skipping",
              file=sys.stderr)
        return None


def _minimal_frontmatter_fallback(fm_text: str, filename: str) -> dict[str, Any] | None:
    """Tiny YAML-subset parser for fallback when pyyaml is absent.

    Supports:
      key: value
      key: [a, b, c]
      key: |
        multi-line block
    """
    data: dict[str, Any] = {}
    lines = fm_text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.startswith("#"):
            i += 1
            continue
        if ":" not in line:
            i += 1
            continue
        key, _, rest = line.partition(":")
        key = key.strip()
        rest = rest.strip()
        if rest.startswith("[") and rest.endswith("]"):
            inner = rest[1:-1]
            data[key] = [s.strip().strip('"').strip("'") for s in inner.split(",") if s.strip()]
        elif rest == "|":
            # Block scalar: gather indented lines below.
            j = i + 1
            block_lines: list[str] = []
            while j < len(lines) and (lines[j].startswith("  ") or not lines[j].strip()):
                block_lines.append(lines[j][2:] if lines[j].startswith("  ") else lines[j])
                j += 1
            data[key] = "\n".join(block_lines).rstrip()
            i = j
            continue
        else:
            data[key] = rest.strip('"').strip("'")
        i += 1
    return data


def _discover_substrate_skills(substrate_skills_dir: Path | None) -> dict[str, SubstrateSkill]:
    """Discover skills under <substrate>/skills/*.md.

    Returns map skill-name -> SubstrateSkill. Malformed files are skipped with
    a WARN. Directory not present -> empty map.
    """
    if substrate_skills_dir is None or not substrate_skills_dir.is_dir():
        return {}
    found: dict[str, SubstrateSkill] = {}
    for child in sorted(substrate_skills_dir.iterdir()):
        if not child.is_file() or child.suffix != ".md":
            continue
        # Filename-derived name. Frontmatter `name` is informational; the
        # filename is the canonical identifier so substrate vs. public
        # collision detection is simple stem-match.
        stem = child.stem
        fm = _parse_skill_frontmatter(child)
        if fm is None:
            continue
        description = str(fm.get("description", "") or "").strip()
        if not description:
            print(f"WARN  skill {child.name} missing 'description' frontmatter; "
                  "rendered slash entry will be empty", file=sys.stderr)
        raw_harnesses = fm.get("supported_harnesses", ["claude", "codex", "kimi"])
        if isinstance(raw_harnesses, str):
            raw_harnesses = [raw_harnesses]
        if not isinstance(raw_harnesses, list):
            raw_harnesses = ["claude", "codex", "kimi"]
        harnesses = tuple(str(h).strip() for h in raw_harnesses if str(h).strip())
        found[stem] = SubstrateSkill(
            name=stem,
            body_path=child.resolve(),
            description=description,
            supported_harnesses=harnesses,
        )
    return found


def skill_wrapper_body(name: str, harness: str, dotpanel_root_str: str,
                       sync_command: str = "dotpanel sync") -> str:
    canonical_rel = f"protocol/skills/{CANONICAL_SKILL_FILES[name]}"
    canonical_abs = f"{dotpanel_root_str}/{canonical_rel}"
    title = SKILL_TITLES[name]
    description = SKILL_DESCRIPTIONS[name]
    invoke = {
        "claude": f"/{name}",
        "codex": f"${name} or the {name} skill selector",
    }[harness]
    surface = f"Thin {harness.capitalize()} skill"

    if name == "review":
        action = (
            "\nParse the user's arguments:"
            f"\n\n- If `--ui` is present, read `{dotpanel_root_str}/protocol/skills/design-audit.md` and execute it."
            f"\n- Otherwise, read `{canonical_abs}` and execute it."
        )
    else:
        action = f"\nRead `{canonical_abs}` and execute its process."

    fm = (
        "---\n"
        f"name: {name}\n"
        f"description: |\n  Use when the user invokes {invoke}. {description} {surface}: delegates to {canonical_abs}.\n"
        "---\n"
    )
    # The `sync` wrapper bakes the substrate-configured sync command into the
    # rendered output (D4 / IC-SS-2). The canonical body at config-sync.md stays
    # methodology-abstract; the concrete command lives only here, in the
    # rendered harness adapter the harness reads at invocation time.
    sync_hint = ""
    if name == "sync":
        sync_hint = (
            f"\n## Configured sync command\n\n"
            f"The substrate's configured sync command is `{sync_command}` "
            f"(from `.dotpanel.toml [harness] sync_command`; defaults to "
            f"`dotpanel sync`). Use this command for `push` / `pull` / `diff` "
            "/ `status` per the canonical body.\n"
        )
    return (
        f"{fm}\n"
        f"{GENERATED_BANNER}\n"
        f"<!-- Source: {canonical_rel} -->\n"
        f"<!-- Update: dotpanel configure --harness {harness} -->\n\n"
        f"# {title}\n\n"
        f"This is a {surface.lower()}. The canonical process lives in `{canonical_abs}`.\n\n"
        "## Action\n"
        f"{action}\n"
        f"{sync_hint}"
    )


def substrate_skill_wrapper_body(skill: SubstrateSkill, harness: str) -> str:
    """Render a skill wrapper for a substrate-discovered skill.

    Substrate skills don't have a hardcoded title/description in cli.py;
    those come from the file's frontmatter. The wrapper points the harness
    at the substrate body file (absolute path baked in at configure time).
    """
    invoke = {
        "claude": f"/{skill.name}",
        "codex": f"${skill.name} or the {skill.name} skill selector",
    }[harness]
    surface = f"Thin {harness.capitalize()} skill"
    canonical_abs = str(skill.body_path)
    title = skill.name.replace("-", " ").replace("_", " ").title()
    description = skill.description or (
        f"Substrate-private skill (frontmatter description missing in {skill.body_path.name})"
    )
    fm = (
        "---\n"
        f"name: {skill.name}\n"
        f"description: |\n  Use when the user invokes {invoke}. {description} {surface}: delegates to {canonical_abs}.\n"
        "---\n"
    )
    return (
        f"{fm}\n"
        f"{GENERATED_BANNER}\n"
        f"<!-- Source (substrate): {canonical_abs} -->\n"
        f"<!-- Update: dotpanel configure --harness {harness} -->\n\n"
        f"# {title}\n\n"
        f"This is a {surface.lower()}. The canonical process lives in "
        f"`{canonical_abs}`.\n\n"
        "## Action\n"
        f"\nRead `{canonical_abs}` and execute its process.\n"
    )


# ---------------------------------------------------------------------------
# Subcommand: root
# ---------------------------------------------------------------------------

def cmd_root() -> int:
    print(dotpanel_root())
    return 0


# ---------------------------------------------------------------------------
# Subcommand: version (handled by --version flag, but also as subcommand)
# ---------------------------------------------------------------------------

def cmd_version() -> int:
    print(f"dotpanel {__version__}")
    return 0


# ---------------------------------------------------------------------------
# Subcommand: doctor
# ---------------------------------------------------------------------------

def cmd_doctor(paths: DotpanelPaths,
               *, skip_stale_rename: bool = False) -> int:
    """Verify install, symlink, persona, templates, paths.

    Implements the consolidated 15-row invariants table (IC-SG-4). FAIL items
    accumulate; WARN items print to stderr but don't change exit code unless
    a FAIL was also recorded.

    `skip_stale_rename` is accepted for back-compat with internal callers
    that pre-date the removal of the stale-rename detector; it has no effect.
    """
    issues: list[str] = []
    warnings: list[str] = []

    # Required directories under dotpanel root
    for required in (paths.protocol, paths.protocol / "skills", paths.protocol / "rules",
                     paths.protocol / "workspace.md", paths.harness, paths.claude_templates,
                     paths.codex_templates, paths.kimi_templates):
        if not required.exists():
            issues.append(f"MISSING required path: {required}")

    # pyproject.toml at root (editable-install relocation guard)
    pyproject = paths.root / "pyproject.toml"
    if not pyproject.exists():
        issues.append(
            f"pyproject.toml missing at {pyproject}. "
            "Repo may have been moved without re-running 'pip install -e .'"
        )

    # Editable install pointing at this source location
    try:
        spec = importlib.util.find_spec("dotpanel")
        if spec and spec.origin:
            installed = Path(spec.origin).resolve().parents[0]
            source = paths.root / "dotpanel"
            if installed.resolve() != source.resolve():
                issues.append(
                    f"dotpanel installed at {installed} but source at {source}. "
                    f"Re-run 'pip install -e .' from {paths.root}"
                )
    except Exception as exc:
        issues.append(f"editable-install detection failed: {exc}")

    # Persona symlink
    persona_link = paths.root / "persona"
    if not persona_link.exists():
        issues.append(
            f"persona symlink missing at {persona_link}. "
            "Run `dotpanel init [--persona-root <path>]` to create."
        )
    else:
        if not persona_link.is_symlink():
            issues.append(f"persona at {persona_link} is not a symlink (expected symlink)")
        else:
            target = persona_link.resolve()
            if not target.is_dir():
                issues.append(f"persona symlink target {target} is not a directory")

        # Required persona files exist at flat root
        if not (persona_link / "voice.md").exists():
            issues.append(f"persona/voice.md missing at {persona_link / 'voice.md'}")
        if not (persona_link / "identity.yaml").exists():
            issues.append(f"persona/identity.yaml missing at {persona_link / 'identity.yaml'}")

    # Templates exist
    for template in (paths.claude_templates / "CLAUDE.md", paths.claude_templates / "settings.json",
                     paths.codex_templates / "AGENTS.md", paths.codex_templates / "config.toml",
                     paths.kimi_templates / "AGENTS.md"):
        if not template.exists():
            issues.append(f"MISSING template: {template}")

    # Invariant 7 + 8: .dotpanel.toml schema validation + path traversal (H9).
    # Both are surfaced via the config loader; loader raises SchemaError on
    # path-traversal or other invariant violations. We just call find_substrate
    # and treat SchemaError as FAIL. SubstrateNotFound is NOT a failure —
    # operators may run dotpanel from a tmp dir without a substrate.
    try:
        find_substrate()
    except SubstrateNotFound:
        pass  # legal — no substrate discoverable
    except Exception as exc:
        # SchemaError (path-traversal, type errors, etc.) or unexpected
        # exceptions from TOML parsing -> FAIL.
        issues.append(f".dotpanel.toml schema validation: {exc}")

    # Invariant 11: age + age-keygen binaries on PATH (H6). FAIL because
    # secrets verbs are unusable without them.
    for binary in ("age", "age-keygen"):
        if shutil.which(binary) is None:
            issues.append(
                f"`{binary}` binary not on PATH. Install:\n"
                f"      macOS:    brew install age\n"
                f"      Debian:   apt install age\n"
                f"      Other:    https://github.com/FiloSottile/age/releases"
            )

    # Invariant 10: launcher PATH resolution (WARN). `claw` and `codx` must
    # resolve under <dotpanel-root>/tools/bin/ — otherwise another binary on
    # PATH is shadowing the dotpanel launcher. (Substrate-side shims in
    # the configured substrate_bin dir also count as valid.)
    bundled_bin = (paths.root / "tools" / "bin").resolve()
    for launcher in ("claw", "codx"):
        resolved = shutil.which(launcher)
        if resolved is None:
            warnings.append(
                f"`{launcher}` not on PATH. Open a new shell, or "
                f"`source ~/.config/dotpanel/path.sh` in this one."
            )
            continue
        resolved_path = Path(resolved).resolve()
        # Allow shim paths (substrate's tools/bin may host shims that exec
        # the bundled launcher) — only warn when resolved path is in neither
        # the bundled dir nor the configured substrate bin.
        substrate_bin = _try_find_substrate()
        substrate_bin_path: Path | None = None
        if substrate_bin is not None and substrate_bin.configure is not None:
            substrate_bin_path = substrate_bin.configure.substrate_bin.resolve()
        ok = (resolved_path.parent == bundled_bin
              or (substrate_bin_path is not None
                  and resolved_path.parent == substrate_bin_path))
        if not ok:
            warnings.append(
                f"`{launcher}` resolves to {resolved_path} (expected "
                f"{bundled_bin}/{launcher}). Another binary named `{launcher}` "
                f"on PATH is shadowing the dotpanel launcher."
            )

    # Invariant 9: backend vs llm_scope coherence (WARN). Every
    # [backends.*].variants.*.key should match at least one [secrets]
    # llm_scope fnmatch pattern. Mismatched keys mean the variant works for
    # the launcher but vscode-server (which inherits via `secrets export
    # --scope llm`) does NOT have the key.
    sub = _try_find_substrate()
    if sub is not None:
        import fnmatch as _fnmatch
        llm_patterns = list(sub.secrets.llm_scope)
        if llm_patterns:
            for provider_name, provider in sub.backends.providers.items():
                for variant_name, variant in provider.variants.items():
                    key = variant.key
                    if not key:
                        continue
                    if not any(_fnmatch.fnmatchcase(key, p) for p in llm_patterns):
                        warnings.append(
                            f"backends.{provider_name}.variants.{variant_name}.key "
                            f"= {key!r} does not match any [secrets] "
                            f"llm_scope pattern. `{provider_name} --{variant_name}` "
                            "will work, but vscode-server (which inherits via "
                            "`secrets export --scope llm`) will NOT have this key."
                        )

    # Invariant 16: VSCode Codex extension needs server-env-setup so the
    # extension host inherits env_key-based LLM credentials.
    for vscode_home_name in (".vscode-server", ".vscode-server-insiders"):
        vscode_home = paths.home / vscode_home_name
        extensions_dir = vscode_home / "extensions"
        if not extensions_dir.is_dir():
            continue
        has_codex_extension = any(
            child.is_dir() and child.name.startswith("openai.chatgpt-")
            for child in extensions_dir.iterdir()
        )
        if has_codex_extension and not (vscode_home / "server-env-setup").is_file():
            warnings.append(
                f"{vscode_home}/server-env-setup missing. VSCode Codex extension "
                "may not inherit LLM env keys; install a setup file that runs "
                "`dotpanel secrets export --scope llm` before vscode-server starts."
            )

    # Invariant 12: multi-checkout detection (WARN). `pip show dotpanel`
    # should show exactly one editable install. This is best-effort: the
    # active editable install plus an in-repo legacy `dotpanel.egg-info/`
    # directory both register as distributions; only WARN when two different
    # SOURCE locations are detected (not when egg-info shadows the same source).
    try:
        import importlib.metadata as _md
        dists = list(_md.distributions())
        dotpanel_dists = [d for d in dists if d.metadata["Name"] == "dotpanel"]
        if len(dotpanel_dists) > 1:
            # Resolve each distribution to its actual source dir (where
            # dotpanel/cli.py lives). For dev-mode egg-info in the source
            # repo, that's the repo root. For a real editable install,
            # we read the .pth file or follow PackagePath relpaths.
            source_dirs: set[str] = set()
            for d in dotpanel_dists:
                # Walk to dotpanel/__init__.py and take its parent.
                for fp in (d.files or []):
                    if str(fp).endswith("dotpanel/__init__.py"):
                        try:
                            abs_path = Path(str(d.locate_file(fp))).resolve()
                            source_dirs.add(str(abs_path.parents[1]))
                        except (OSError, ValueError):
                            pass
                        break
            if len(source_dirs) > 1:
                warnings.append(
                    f"multiple `dotpanel` source checkouts detected:\n        "
                    + "\n        ".join(sorted(source_dirs))
                    + "\n      Run `pip uninstall dotpanel` until only one "
                    "editable install remains; then `pip install -e .` from "
                    "the canonical source dir."
                )
    except Exception:
        # Best-effort; metadata can fail in odd environments.
        pass

    # Invariant 13: stuck sync-state check (per design doc C6 doctor invariant).
    try:
        from .sync import _load_state, STUCK_AGE_SECONDS
        state = _load_state(paths.home)
        if state.is_active() and state.age_seconds() > STUCK_AGE_SECONDS:
            issues.append(
                f"stuck sync state at phase {state.phase!r} "
                f"(age {int(state.age_seconds())}s); run 'dotpanel sync resume' "
                "or 'dotpanel sync pull --force-restart'"
            )
    except Exception as exc:
        # Don't fail doctor if state loader is broken — just surface the warning.
        print(f"WARN  sync state check failed: {exc}", file=sys.stderr)

    # Report
    for warn in warnings:
        print(f"WARN  {warn}", file=sys.stderr)
    if issues:
        for issue in issues:
            print(f"FAIL  {issue}")
        return 2
    print(f"OK  dotpanel doctor passed (root: {paths.root})")
    return 0


# ---------------------------------------------------------------------------
# Subcommand: init
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# v5 init seed templates (per design "dotpanel init Seed Template")
# ---------------------------------------------------------------------------

# Minimal .dotpanel.toml content for a fresh substrate. Includes only what
# satisfies `dotpanel doctor` after `init`; forkers grow it incrementally.
_INIT_DOTPANEL_TOML = """\
[dotpanel]
schema_version = "1.0"

[paths]
persona = "persona"
# Uncomment as your substrate grows:
# skills = "skills"
# infra = "infra"
# install_pins = "install-pins.sh"
# network_nodes = "tools/network/nodes.yaml"

[harness]
enabled = ["claude", "codex", "kimi"]
# sync_command = "dotpanel sync"  # default

# [sync]
# repos = []                       # add repos to sync (path + label per entry)
# leak_mode_default = "generic"

# [secrets]
# llm_scope = ["ANTHROPIC_*", "OPENAI_*", "CLAUDE_*"]
"""

_INIT_SKILLS_README = """\
# Substrate skills

Drop `*.md` files here (with YAML frontmatter) to extend or override the
public skill palette. Substrate skills override public skills on filename
collision (per D7), so a file named `review.md` here replaces the public
`/review` content for this substrate.

Frontmatter schema:

```yaml
---
name: my-team-pattern
description: Use when the user invokes /my-team-pattern. <one-line trigger>
type: skill
supported_harnesses: [claude, codex]
---
```

After dropping a skill file here, run `dotpanel configure --harness all`
to render the new wrapper into harness-native skill homes such as
`~/.claude/skills/<name>/SKILL.md` and `~/.agents/skills/<name>/SKILL.md`
for Codex.

Skills can be selectively disabled or harness-scoped in `.dotpanel.toml`:

```toml
[skills]
disabled = ["my-team-pattern"]

[skills.review]
harnesses = ["claude"]  # only render /review for claude
```
"""

_INIT_EXAMPLE_BACKUP_TEMPLATE = """\
#!/usr/bin/env bash
# example-backup.sh - substrate-private credential-injecting ops verb (EC-9)
# Rename this file (drop .template) and `chmod +x` to activate.
#
# Pattern: shell through `dotpanel secrets run --key X -- python3 helper.py "$@"`
# to inject only the keys this verb needs. Per-key scope; no bulk decrypt.
#
# Examples:
#   dotpanel secrets run --key MY_CLOUD_KEY -- python3 helper.py "$@"
#   dotpanel secrets run --key TENCENT_SECRET_ID --key TENCENT_SECRET_KEY -- \\
#       python3 tools/lib/backup.py "$@"
set -euo pipefail
exec dotpanel secrets run --key MY_CLOUD_KEY -- python3 path/to/helper.py "$@"
"""


def _write_init_file_if_missing(path: Path, body: str, *, executable: bool = False,
                                results: list[str] | None = None) -> None:
    """Write `body` to `path` only if the file doesn't exist yet.

    Idempotent: `dotpanel init` can be re-run on an existing substrate
    without clobbering operator content. Returns nothing; appends a status
    string to `results` if provided.
    """
    if path.exists():
        if results is not None:
            results.append(f"OK  skill skeleton already exists: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)
    if executable:
        path.chmod(0o755)
    if results is not None:
        results.append(f"WROTE  {path}")


def _seed_v5_substrate_skeleton(substrate_root: Path) -> list[str]:
    """Lay down the v5 substrate skeleton inside `substrate_root`.

    Creates (if missing):
      - skills/ dir + README.md describing the override mechanism
      - tools/bin/ dir + example-backup.sh.template commented script
      - .dotpanel.toml with [dotpanel] schema_version + [paths] persona

    All writes are idempotent; existing files are NEVER overwritten.
    """
    results: list[str] = []
    # skills/ scaffold
    skills_dir = substrate_root / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)
    _write_init_file_if_missing(skills_dir / "README.md", _INIT_SKILLS_README,
                                results=results)
    # tools/bin/ scaffold
    tools_bin = substrate_root / "tools" / "bin"
    tools_bin.mkdir(parents=True, exist_ok=True)
    _write_init_file_if_missing(tools_bin / "example-backup.sh.template",
                                _INIT_EXAMPLE_BACKUP_TEMPLATE, results=results)
    # Minimal .dotpanel.toml (only if absent — never overwrite an operator's
    # existing config).
    _write_init_file_if_missing(substrate_root / ".dotpanel.toml",
                                _INIT_DOTPANEL_TOML, results=results)
    return results


def cmd_init(paths: DotpanelPaths, persona_root: Path | None) -> int:
    """Create or repair the dotpanel/persona symlink + v5 substrate skeleton.

    v5 changes (per design "dotpanel init Seed Template"):
      - Lay down `<substrate>/skills/` (with README) — substrate-private skills.
      - Lay down `<substrate>/tools/bin/` (with example-backup.sh.template).
      - Write a minimal `.dotpanel.toml` to substrate root if absent.
      - Print a post-init hint covering PATH sourcing + secrets init + configure.

    The substrate root is the parent of the persona target dir.
    """
    persona_link = paths.root / "persona"

    # Default substrate convention: ~/.dotfiles/persona/. Operator can
    # override with --persona-root to point anywhere.
    target = (persona_root or (paths.home / ".dotfiles" / "persona")).expanduser().resolve()

    # Seed the substrate skeleton when running with defaults — first-time
    # init should leave a usable workspace without forcing the operator to
    # hand-create stub files. Pre-existing files are never overwritten.
    target.mkdir(parents=True, exist_ok=True)
    voice = target / "voice.md"
    identity = target / "identity.yaml"
    if not voice.exists():
        voice.write_text("# Voice\n\nDescribe how you want the agent to talk.\n", encoding="utf-8")
        print(f"WROTE  stub {voice}")
    if not identity.exists():
        identity.write_text("name: \"\"\nemail: \"\"\n", encoding="utf-8")
        print(f"WROTE  stub {identity}")

    if not target.is_dir():
        print(f"FAIL  persona-root {target} is not a directory", file=sys.stderr)
        return 2
    if not voice.exists() or not identity.exists():
        print(
            f"FAIL  persona-root {target} missing voice.md or identity.yaml.",
            file=sys.stderr,
        )
        return 2

    # Create or repair symlink
    if persona_link.is_symlink():
        if persona_link.resolve() == target:
            print(f"OK  persona symlink already pointing to {target}")
        else:
            print(f"REPLACE  persona symlink: {persona_link.resolve()} -> {target}")
            persona_link.unlink()
            persona_link.symlink_to(target)
    elif persona_link.exists():
        print(
            f"FAIL  {persona_link} exists and is not a symlink. Move it aside or delete first.",
            file=sys.stderr,
        )
        return 2
    else:
        persona_link.symlink_to(target)
        print(f"WROTE  persona symlink: {persona_link} -> {target}")

    # v5: lay down substrate skeleton at the persona's parent directory
    # (substrate root). target is the persona dir, so substrate is target.parent.
    substrate_root = target.parent
    if substrate_root.exists() and substrate_root.is_dir():
        for line in _seed_v5_substrate_skeleton(substrate_root):
            print(line)

    rc = cmd_doctor(paths, skip_stale_rename=True)

    # Auto-inject shell rc (idempotent — safe to run on every init).
    try:
        rc_results = inject_shell_rc(paths.home)
        for rc_status, rc_path in rc_results:
            rc_tag = {"appended": "OK", "noop": "OK"}[rc_status]
            rc_verb = {"appended": "appended source line to",
                       "noop": "source line already present in"}[rc_status]
            print(f"{rc_tag}  {rc_verb} {rc_path}")
    except OSError as exc:
        print(f"WARN  could not inject shell rc: {exc}", file=sys.stderr)

    # Post-init bootstrap hint (per design "Post-init bootstrap hint")
    print()
    print("Next steps:")
    print("  1. dotpanel secrets init --keygen        # create age key + empty bundle")
    print("  2. dotpanel secrets edit                 # add API keys")
    print("  3. dotpanel configure --harness all      # render harness adapters")
    print("  4. dotpanel doctor                       # verify the install")
    return rc


# ---------------------------------------------------------------------------
# Subcommand: configure
# ---------------------------------------------------------------------------

@dataclass
class ConfigureResult:
    actions: list[str] = field(default_factory=list)
    conflicts: list[str] = field(default_factory=list)


def _excluded_path(rel_path: str, harness: str) -> bool:
    excluded = {
        "claude": CLAUDE_EXCLUDED,
        "codex": CODEX_EXCLUDED,
        "kimi": KIMI_EXCLUDED,
    }[harness]
    head = rel_path.split("/", 1)[0]
    if head in excluded:
        return True
    if harness == "codex":
        for glob in CODEX_EXCLUDED_GLOBS:
            if Path(rel_path).match(glob):
                return True
    return False


def _configure_one_file(rel_path: str, content: str, output_root: Path, harness: str,
                        force: bool, dry_run: bool, home: Path,
                        result: ConfigureResult) -> None:
    """Write rel_path under output_root, respecting banner/conflict rules."""
    target = output_root / rel_path
    excluded_rel = rel_path
    if harness == "codex" and rel_path.startswith("skills/"):
        agents_root = home / ".agents"
        if output_root != home / ".codex":
            agents_root = output_root.parent / "agents"
        target = agents_root / rel_path
        excluded_rel = f".agents/{rel_path}"
    if _excluded_path(excluded_rel, harness):
        return  # Never write to excluded paths
    if target.exists():
        if target.is_symlink():
            link_target = target.resolve()
            if str(link_target).startswith(str(dotpanel_root())):
                # legacy symlink into dotpanel — replace
                action = f"REPLACE-LINK {target}"
                if not dry_run:
                    target.unlink()
                    _write_atomic(target, content) if not _is_json(rel_path) else _write_atomic(target, content)
                result.actions.append(action)
                return
            if not force:
                result.conflicts.append(f"symlink to external target: {target} -> {link_target}")
                return
        elif target.is_file():
            if _is_json(rel_path):
                if is_managed_json(target, home) or force:
                    action = f"OVERWRITE-JSON {target}"
                    if not dry_run:
                        _write_atomic(target, content)
                    result.actions.append(action)
                    return
                result.conflicts.append(f"unmanaged JSON at {target}")
                return
            if has_dotpanel_banner(target):
                if target.read_text(encoding="utf-8") == content:
                    # Content match — but still repair exec-bit drift if the
                    # template is a shebang script and the on-disk file lost
                    # its executable bit (e.g., from earlier write before the
                    # exec-bit fix landed).
                    if content.startswith("#!") and not os.access(target, os.X_OK):
                        if not dry_run:
                            os.chmod(target, 0o755)
                        result.actions.append(f"CHMOD+X {target}")
                    return  # noop on content
                action = f"OVERWRITE {target}"
                if not dry_run:
                    _write_atomic(target, content, executable=content.startswith("#!"))
                result.actions.append(action)
                return
            if force:
                action = f"FORCE {target}"
                if not dry_run:
                    _write_atomic(target, content, executable=content.startswith("#!"))
                result.actions.append(action)
                return
            result.conflicts.append(f"non-banner file at {target}")
            return
    # Target doesn't exist — write
    if dry_run:
        result.actions.append(f"WOULD-CREATE {target}")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        _write_atomic(target, content, executable=content.startswith("#!"))
        result.actions.append(f"CREATE {target}")


def _is_json(rel_path: str) -> bool:
    return rel_path.endswith(".json")


def _gather_outputs(paths: DotpanelPaths, harness: str) -> list[tuple[str, str]]:
    """Returns list of (relative_path, rendered_content) tuples for the harness."""
    root_str = str(paths.root)
    outputs: list[tuple[str, str]] = []
    templates = {
        "claude": paths.claude_templates,
        "codex": paths.codex_templates,
        "kimi": paths.kimi_templates,
    }[harness]
    if not templates.exists():
        return outputs

    # Resolve sync_command from substrate config (D4 / IC-SG-1).
    # `[harness] sync_command` overrides; default is "dotpanel sync".
    substrate = _try_find_substrate()
    sync_command = "dotpanel sync"
    if substrate is not None and substrate.harness is not None:
        sync_command = substrate.harness.sync_command or sync_command

    # Top-level template files (CLAUDE.md / settings.json / statusline.py for claude;
    # AGENTS.md / config.toml for codex)
    for template in templates.iterdir():
        if template.is_file():
            content = render_text(template.read_text(encoding="utf-8"), root_str,
                                  sync_command=sync_command)
            outputs.append((template.name, content))
        elif template.is_dir() and template.name != "skills":
            # statusline.py might live in claude/templates/, copy as-is
            for child in template.rglob("*"):
                if child.is_file():
                    rel = str(child.relative_to(templates))
                    content = render_text(child.read_text(encoding="utf-8"), root_str,
                                          sync_command=sync_command)
                    outputs.append((rel, content))

    # Skill wrappers (programmatically generated, not from template files).
    # Kimi currently discovers shared skills from Claude's skill directory on
    # this setup; do not invent a harness-native skills surface without proof.
    if harness == "kimi":
        return outputs

    # D7: substrate skills override public skills on filename collision; the
    # union of substrate + public (minus substrate-claimed filenames) is the
    # final skill set. `[skills] disabled` list blacklists names from both.
    # Per-skill harness scoping: substrate skills use frontmatter
    # `supported_harnesses`; public skills are configurable via
    # `.dotpanel.toml [skills.<name>] harnesses`.
    substrate_skills_dir = _substrate_skills_dir(substrate)
    substrate_skills = _discover_substrate_skills(substrate_skills_dir)

    disabled: set[str] = set()
    per_skill: dict[str, dict[str, Any]] = {}
    if substrate is not None:
        disabled = set(substrate.skills.disabled)
        per_skill = dict(substrate.skills.per_skill)

    # Substrate skills first (claim filenames).
    for name, skill in substrate_skills.items():
        if name in disabled:
            continue
        if harness not in skill.supported_harnesses:
            continue
        # toml override beats frontmatter for harness scope.
        toml_harnesses = per_skill.get(name, {}).get("harnesses")
        if isinstance(toml_harnesses, list) and harness not in toml_harnesses:
            continue
        rel = f"skills/{name}/SKILL.md"
        content = substrate_skill_wrapper_body(skill, harness)
        outputs.append((rel, content))

    # Public skills: skip any name claimed by substrate.
    for name in USER_FACING_SKILLS:
        if name in disabled:
            continue
        if name in substrate_skills:
            continue
        # toml-level per-skill harness scope.
        toml_harnesses = per_skill.get(name, {}).get("harnesses")
        if isinstance(toml_harnesses, list) and harness not in toml_harnesses:
            continue
        rel = f"skills/{name}/SKILL.md"
        content = skill_wrapper_body(name, harness, root_str,
                                     sync_command=sync_command)
        outputs.append((rel, content))

    return outputs


def _substrate_skills_dir(substrate: SubstrateConfig | None) -> Path | None:
    """Resolve <substrate>/skills/ from config.

    Returns None when substrate isn't loaded or [paths] skills is unset/absent.
    """
    if substrate is None or substrate.paths is None:
        return None
    skills = substrate.paths.skills
    if skills is None:
        return None
    return skills if skills.is_dir() else None


# ---------------------------------------------------------------------------
# D5: PATH injection — ~/.config/dotpanel/path.sh
# ---------------------------------------------------------------------------

# Single-line source statement that operators paste into ~/.bashrc / ~/.zshrc.
# Kept as a constant so write_path_sh, inject_shell_rc, and the post-configure
# hint print all use the same string (idempotency relies on byte-equal match).
PATH_SH_REL = ".config/dotpanel/path.sh"
PATH_SH_SOURCE_LINE = (
    "[ -f ~/.config/dotpanel/path.sh ] && source ~/.config/dotpanel/path.sh"
)
# Banner identifying dotpanel-generated path.sh. Whole-file ownership per ADR-3.
PATH_SH_BANNER = "# Generated by dotpanel; do not edit directly."


def _render_path_sh(bundled_bin: Path, substrate_bin: Path | None) -> str:
    """Render the whole-file body of ~/.config/dotpanel/path.sh.

    Bundled bin dir is always injected. Substrate bin dir injected only if
    supplied (resolved by caller from `[configure] substrate_bin`).
    """
    lines = [
        PATH_SH_BANNER,
        "# Source from your shell rc with:",
        f"#   {PATH_SH_SOURCE_LINE}",
        "#",
        "# Re-rendered by `dotpanel configure`. Absolute paths baked in at render time.",
        f'export PATH="{bundled_bin}:$PATH"',
    ]
    if substrate_bin is not None:
        lines.append(f'export PATH="{substrate_bin}:$PATH"')
    return "\n".join(lines) + "\n"


def write_path_sh(home: Path, dotpanel_root: Path, substrate_bin: Path | None,
                  *, dry_run: bool = False) -> tuple[str, Path]:
    """Write ~/.config/dotpanel/path.sh atomically.

    Returns (status, path) where status is one of "wrote", "noop", "would".
    Idempotent: rewrites only when content actually differs.
    """
    target = home / PATH_SH_REL
    bundled_bin = (dotpanel_root / "tools" / "bin").resolve()
    body = _render_path_sh(bundled_bin, substrate_bin)
    if target.exists():
        try:
            if target.read_text(encoding="utf-8") == body:
                return "noop", target
        except OSError:
            pass
    if dry_run:
        return "would", target
    target.parent.mkdir(parents=True, exist_ok=True)
    _write_atomic(target, body)
    return "wrote", target


def _detect_shell_rcs(home: Path) -> list[Path]:
    """Return the list of shell rc files to inject into.

    Detects bash + zsh on best-effort basis. Targets:
      - ~/.bashrc if it exists OR $SHELL ends in /bash
      - ~/.bash_profile if it exists (login shells like SSH read this, not .bashrc)
      - ~/.zshrc if it exists OR $SHELL ends in /zsh
      - ~/.zprofile if it exists (zsh login shells)
    If none exists, defaults to whatever $SHELL says, falling back to ~/.bashrc.
    """
    rcs: list[Path] = []
    shell = os.environ.get("SHELL", "")
    bashrc = home / ".bashrc"
    bash_profile = home / ".bash_profile"
    zshrc = home / ".zshrc"
    zprofile = home / ".zprofile"
    if bashrc.exists() or shell.endswith("/bash"):
        rcs.append(bashrc)
    if bash_profile.exists():
        rcs.append(bash_profile)
    if zshrc.exists() or shell.endswith("/zsh"):
        rcs.append(zshrc)
    if zprofile.exists():
        rcs.append(zprofile)
    if not rcs:
        rcs.append(bashrc)  # last resort: bash is the dominant default
    return rcs


def inject_shell_rc(home: Path, *, dry_run: bool = False) -> list[tuple[str, Path]]:
    """Append the path.sh source line to detected shell rc files.

    Idempotent: scans each rc for an existing line matching PATH_SH_SOURCE_LINE
    (byte-equal after strip) and skips if already present. Returns a list of
    (status, path) tuples where status is "appended", "noop", or "would".
    """
    results: list[tuple[str, Path]] = []
    target_line = PATH_SH_SOURCE_LINE.strip()
    for rc in _detect_shell_rcs(home):
        already = False
        if rc.exists():
            try:
                for line in rc.read_text(encoding="utf-8").splitlines():
                    if line.strip() == target_line:
                        already = True
                        break
            except OSError:
                already = False
        if already:
            results.append(("noop", rc))
            continue
        if dry_run:
            results.append(("would", rc))
            continue
        rc.parent.mkdir(parents=True, exist_ok=True)
        # Append (rather than rewrite) — minimal touch on operator-owned content.
        with rc.open("a", encoding="utf-8") as fh:
            # Pad with a leading newline so we never glue onto a prior non-newline.
            if rc.exists() and rc.stat().st_size > 0:
                # Ensure we start on a fresh line.
                # Re-reading is cheap; safer than assuming the file ended in \n.
                last = rc.read_text(encoding="utf-8")[-1:] if rc.stat().st_size else "\n"
                if last != "\n":
                    fh.write("\n")
            fh.write(f"# dotpanel: launcher PATH (idempotent)\n")
            fh.write(f"{PATH_SH_SOURCE_LINE}\n")
        results.append(("appended", rc))
    return results


def _resolve_substrate_bin(substrate: SubstrateConfig | None,
                           include_substrate_bin: bool | None) -> Path | None:
    """Decide whether (and which) substrate tools/bin dir to inject.

    Returns None when the substrate dir is unknown or explicitly disabled.
    `include_substrate_bin=True`  -> always include (FAIL if dir absent).
    `include_substrate_bin=False` -> never include.
    `include_substrate_bin=None`  -> auto: include iff resolved dir exists.
    """
    if include_substrate_bin is False:
        return None
    if substrate is None or substrate.configure is None:
        return None
    candidate = substrate.configure.substrate_bin
    if not candidate.is_dir():
        # In auto mode (None), missing dir means skip silently. In explicit
        # True mode the caller will surface this as a warning.
        return None
    return candidate.resolve()


def _try_find_substrate() -> SubstrateConfig | None:
    """Best-effort substrate discovery; never raises out of configure flow."""
    try:
        return find_substrate()
    except SubstrateNotFound:
        return None
    except Exception:
        return None


def _current_managed_skill_names(paths: DotpanelPaths) -> set[str]:
    """Compute the full set of skill names dotpanel currently manages (any harness).

    Union of:
      - USER_FACING_SKILLS (public skills from cli.py registry)
      - <substrate>/skills/*.md (D7 substrate-private skills)
    Minus any names listed in `.dotpanel.toml [skills] disabled`.

    This is the GLOBAL set — used for the managed-skills.json registry file.
    For prune decisions, use `_managed_skill_names_for_harness` instead, since
    a skill can declare `supported_harnesses: [claude]` and still belong in the
    registry while being an orphan on codex's side.
    """
    names: set[str] = set(USER_FACING_SKILLS)
    substrate = _try_find_substrate()
    if substrate is not None:
        substrate_skills_dir = _substrate_skills_dir(substrate)
        names |= set(_discover_substrate_skills(substrate_skills_dir))
        names -= set(substrate.skills.disabled)
    return names


def _managed_skill_names_for_harness(paths: DotpanelPaths, harness: str) -> set[str]:
    """Per-harness subset of managed skills — skills that SHOULD render into
    THIS harness's skill directory under current config.

    Honors substrate skill frontmatter `supported_harnesses`, public skill
    `.dotpanel.toml [skills.<name>] harnesses` overrides, and `[skills] disabled`.
    Mirrors the gating logic in `_gather_outputs` so prune sees the same view.
    """
    substrate = _try_find_substrate()
    disabled: set[str] = set()
    per_skill: dict[str, Any] = {}
    if substrate is not None:
        disabled = set(substrate.skills.disabled)
        per_skill = dict(substrate.skills.per_skill)

    substrate_skills_dir = _substrate_skills_dir(substrate) if substrate else None
    substrate_skills = _discover_substrate_skills(substrate_skills_dir) if substrate_skills_dir else {}

    names: set[str] = set()
    # Substrate skills with this harness supported
    for name, skill in substrate_skills.items():
        if name in disabled:
            continue
        if harness not in skill.supported_harnesses:
            continue
        toml_harnesses = per_skill.get(name, {}).get("harnesses")
        if isinstance(toml_harnesses, list) and harness not in toml_harnesses:
            continue
        names.add(name)

    # Public skills not claimed by substrate (substrate overrides public on collision)
    for name in USER_FACING_SKILLS:
        if name in substrate_skills:
            continue
        if name in disabled:
            continue
        toml_harnesses = per_skill.get(name, {}).get("harnesses")
        if isinstance(toml_harnesses, list) and harness not in toml_harnesses:
            continue
        names.add(name)

    return names


def _managed_skills_registry_path(home: Path) -> Path:
    """Path to ~/.dotpanel/managed-skills.json (C12 registry)."""
    return home / ".dotpanel" / "managed-skills.json"


def _actual_skills_dir(paths: DotpanelPaths, harness: str) -> Path | None:
    """Harness-native skills directory for generated user-facing wrappers."""
    return paths.skills_root(harness, None)


def _write_managed_skills_registry(home: Path, names: list[str], harnesses: list[str],
                                   *, dry_run: bool) -> None:
    """Atomically write the managed-skills registry.

    Schema:
        {
          "schema_version": "1",
          "skills": ["plan", "review", "ship", "sync", "tool", "wrap"],
          "harnesses": ["claude", "codex", "kimi"],
          "written_at": "<iso-utc>"
        }
    """
    if dry_run:
        return
    payload = {
        "schema_version": "1",
        "skills": sorted(set(names)),
        "harnesses": sorted(set(harnesses)),
    }
    import datetime as _dt
    payload["written_at"] = _dt.datetime.now(_dt.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )
    target = _managed_skills_registry_path(home)
    target.parent.mkdir(parents=True, exist_ok=True)
    _write_atomic(target, json.dumps(payload, indent=2, sort_keys=True) + "\n")


def _prune_orphan_skills(paths: DotpanelPaths,
                        harnesses: list[str], *, dry_run: bool,
                        result: "ConfigureResult") -> None:
    """Remove ~/.<harness>/skills/<orphan>/ for skills not valid in that harness.

    Uses per-harness `_managed_skill_names_for_harness` so that a skill declaring
    `supported_harnesses: [claude]` correctly looks like an orphan from codex's
    perspective even though it remains in the global managed-skills registry.

    Each orphan dir must contain a banner-marked SKILL.md (so we don't delete
    user-created skill directories). Empty parent skill/ dirs after removal
    are left in place.
    """
    for harness in harnesses:
        if harness == "kimi":
            # kimi has no native skills surface in this setup; nothing to prune.
            continue
        try:
            home = paths.output_root(harness, None)
        except ValueError:
            continue
        skills_dir = _actual_skills_dir(paths, harness)
        if skills_dir is None:
            continue
        if not skills_dir.is_dir():
            continue
        valid_for_harness = _managed_skill_names_for_harness(paths, harness)
        for child in sorted(skills_dir.iterdir()):
            if not child.is_dir():
                continue
            if child.name in valid_for_harness:
                continue
            skill_md = child / "SKILL.md"
            if not skill_md.is_file():
                continue
            # Only prune banner-marked skills (dotpanel-managed).
            if not has_dotpanel_banner(skill_md):
                result.conflicts.append(
                    f"orphan skill at {child} lacks dotpanel banner; "
                    "leaving in place"
                )
                continue
            action = f"PRUNE-SKILL {child}"
            if not dry_run:
                try:
                    # Remove the SKILL.md (and any other banner files) plus the
                    # directory itself if empty.
                    for f in child.rglob("*"):
                        if f.is_file():
                            f.unlink()
                    for d in sorted(child.rglob("*"), key=lambda p: -len(str(p))):
                        if d.is_dir() and not any(d.iterdir()):
                            d.rmdir()
                    if not any(child.iterdir()):
                        child.rmdir()
                except OSError as exc:
                    result.conflicts.append(f"prune {child} failed: {exc}")
                    continue
            result.actions.append(action)


def cmd_configure(paths: DotpanelPaths, harness: str, check: bool, force: bool,
                  dry_run: bool, output_dir: Path | None,
                  *, include_substrate_bin: bool | None = None,
                  inject_shell_rc_flag: bool = False,
                  prune_orphan_skills: bool = False) -> int:
    """Render harness adapters from templates."""
    # Validate prerequisites. Skip the stale-rename invariant here — configure
    # is exactly the thing that re-renders harness output to clear it, so
    # gating configure on it would create a chicken-and-egg cycle during
    # cutover (operator can't run configure to fix the stale-rename FAILs
    # because configure's doctor preflight refuses).
    doctor_rc = cmd_doctor(paths, skip_stale_rename=True)
    if doctor_rc != 0:
        print("FAIL  dotpanel doctor preconditions not met; resolve before configure.", file=sys.stderr)
        return doctor_rc

    targets = ("claude", "codex", "kimi") if harness == "all" else (harness,)
    overall_result = ConfigureResult()

    # `--check` runs the same planner as the real configure, but with dry_run=True
    # so no files are written. This catches placeholder bugs AND conflict-handling
    # failures (non-banner files at managed paths, foreign symlinks, etc.) per ADR-3.
    plan_dry_run = dry_run or check

    for target in targets:
        out_root = paths.output_root(target, output_dir)
        outputs = _gather_outputs(paths, target)
        if not outputs:
            print(f"WARN  no templates for harness {target}", file=sys.stderr)
            continue
        for rel, content in outputs:
            # Validate placeholder rendering on every output (catches template bugs)
            if "{{" in content or "}}" in content:
                overall_result.conflicts.append(f"{target}/{rel}: unrendered placeholder in output")
            # Run the conflict planner (also in --check mode, just without writes)
            _configure_one_file(rel, content, out_root, target, force, plan_dry_run, paths.home, overall_result)

    if check:
        if overall_result.conflicts:
            for c in overall_result.conflicts:
                print(f"CHECK-FAIL  {c}", file=sys.stderr)
            return 2
        print(f"OK  configure --check passed (targets: {','.join(targets)})")
        return 0

    if overall_result.conflicts:
        for c in overall_result.conflicts:
            print(f"CONFLICT  {c}", file=sys.stderr)
        return 2

    # Mark successful configure for ADR-3 audit cutover-state detection
    if not dry_run and overall_result.actions:
        try:
            dotpanel_state_dir = paths.home / ".dotpanel"
            dotpanel_state_dir.mkdir(parents=True, exist_ok=True)
            _write_atomic(dotpanel_state_dir / "last-configure-success",
                          f"{','.join(targets)}\n")
        except OSError:
            pass

    # C12: write managed-skills registry (after successful planning, before
    # prune so prune sees the up-to-date current_names set).
    current_names = _current_managed_skill_names(paths)
    if not dry_run:
        try:
            _write_managed_skills_registry(
                paths.home, list(current_names), list(targets), dry_run=dry_run,
            )
        except OSError as exc:
            print(f"WARN  could not write managed-skills registry: {exc}",
                  file=sys.stderr)

    # C12: orphan prune (off by default; opt-in via --prune-orphan-skills).
    if prune_orphan_skills:
        _prune_orphan_skills(paths, list(targets),
                             dry_run=dry_run, result=overall_result)

    for action in overall_result.actions:
        print(f"{'WOULD' if dry_run else 'OK'}  {action}")
    if not overall_result.actions:
        print("OK  configuration already current")

    # D5: PATH injection. Write ~/.config/dotpanel/path.sh and optionally
    # append the source line to ~/.bashrc / ~/.zshrc. Both writes are
    # idempotent. Path injection is skipped in --output-dir mode (sandbox)
    # because the operator's $HOME isn't the rendering target.
    if output_dir is None:
        substrate = _try_find_substrate()
        substrate_bin = _resolve_substrate_bin(substrate, include_substrate_bin)
        try:
            status, target = write_path_sh(paths.home, paths.root, substrate_bin,
                                           dry_run=dry_run)
        except OSError as exc:
            print(f"WARN  could not write {paths.home / PATH_SH_REL}: {exc}",
                  file=sys.stderr)
        else:
            tag = {"wrote": "OK", "noop": "OK", "would": "WOULD"}[status]
            verb = {"wrote": "wrote", "noop": "current",
                    "would": "would-write"}[status]
            print(f"{tag}  {verb} {target}")
            if status == "wrote":
                print(
                    f"Add this line to ~/.bashrc / ~/.zshrc to activate launchers:\n"
                    f"    {PATH_SH_SOURCE_LINE}"
                )
        if inject_shell_rc_flag:
            try:
                rc_results = inject_shell_rc(paths.home, dry_run=dry_run)
            except OSError as exc:
                print(f"WARN  could not inject shell rc: {exc}", file=sys.stderr)
            else:
                for rc_status, rc_path in rc_results:
                    rc_tag = {"appended": "OK", "noop": "OK",
                              "would": "WOULD"}[rc_status]
                    rc_verb = {"appended": "appended source line to",
                               "noop": "source line already present in",
                               "would": "would-append source line to"}[rc_status]
                    print(f"{rc_tag}  {rc_verb} {rc_path}")
    return 0


# ---------------------------------------------------------------------------
# Subcommand: audit
# ---------------------------------------------------------------------------

def cmd_audit(paths: DotpanelPaths) -> int:
    """Structural invariants for CI/pre-commit. Per ADR-3 Audit Surface."""
    issues: list[str] = []

    # 1. Persona symlink target exists and is dir
    persona_link = paths.root / "persona"
    if persona_link.exists():
        if not persona_link.is_symlink():
            issues.append(f"persona at {persona_link} should be a symlink")
        else:
            target = persona_link.resolve()
            if not target.is_dir():
                issues.append(f"persona symlink target {target} is not a directory")

    # 2. Required persona files exist at flat root
    if persona_link.exists():
        if not (persona_link / "voice.md").exists():
            issues.append("persona/voice.md missing")
        if not (persona_link / "identity.yaml").exists():
            issues.append("persona/identity.yaml missing")

    # 3. DOTPANEL_MANAGED_JSON list visibility
    print(f"INFO  DOTPANEL_MANAGED_JSON: {DOTPANEL_MANAGED_JSON}")

    # 4. Generated files in harness homes carry banner. Before the first
    # successful configure (no ~/.dotpanel/last-configure-success marker),
    # missing banners are INFO; afterwards they are FAIL (regression check).
    last_configure = paths.home / ".dotpanel" / "last-configure-success"
    cutover_done = last_configure.exists()
    for harness, home_dir, excluded in (
        ("claude", paths.claude_home, CLAUDE_EXCLUDED),
        ("codex", paths.codex_home, CODEX_EXCLUDED),
        ("kimi", paths.kimi_home, KIMI_EXCLUDED),
    ):
        if not home_dir.exists():
            continue
        candidate_paths = []
        for known in ("CLAUDE.md", "AGENTS.md", "settings.json", "config.toml"):
            p = home_dir / known
            if p.exists():
                candidate_paths.append(p)
        skills_dir = _actual_skills_dir(paths, harness)
        if skills_dir is not None and skills_dir.is_dir():
            for skill_md in skills_dir.glob("*/SKILL.md"):
                candidate_paths.append(skill_md)
        for p in candidate_paths:
            try:
                rel = str(p.relative_to(home_dir))
            except ValueError:
                rel = str(p.relative_to(paths.home))
            if _excluded_path(rel, harness):
                continue
            if _is_json(p.name):
                if not is_managed_json(p, paths.home):
                    continue
                continue
            if not has_dotpanel_banner(p):
                msg = f"{p}: no dotpanel banner"
                if cutover_done:
                    issues.append(msg)
                else:
                    print(f"INFO  {msg} (pre-configure file)")

    # 5. Persona excluded from dist artifacts — full inspection delegated to
    # `dotpanel audit --dist`; the default audit only flags presence.
    dist = paths.root / "dist"
    if dist.exists() and any(dist.iterdir()):
        print(
            "INFO  Build artifacts present in dist/. "
            "Run `dotpanel audit --dist` for full member inspection."
        )

    if issues:
        for issue in issues:
            print(f"FAIL  {issue}")
        return 2
    print("OK  dotpanel audit passed")
    return 0


def _archive_members(archive: Path) -> Iterable[str]:
    """Yield member names (POSIX-style paths) from a wheel or sdist archive.

    Wheels are zip; sdists are gzipped tar. Other extensions are skipped by the
    caller. Raises on unreadable archives so audit exits non-zero loudly.
    """
    name = archive.name
    if name.endswith(".whl") or name.endswith(".zip"):
        with zipfile.ZipFile(archive) as zf:
            for member in zf.namelist():
                yield member
    elif name.endswith(".tar.gz") or name.endswith(".tgz"):
        with tarfile.open(archive, mode="r:gz") as tf:
            for member in tf.getnames():
                yield member


def cmd_audit_dist(paths: DotpanelPaths) -> int:
    """Inspect built dist artifacts; FAIL if any persona content leaked.

    Per ADR-2: dotpanel/persona is a gitignored symlink and MANIFEST.in carries
    `prune persona`, but build tooling can still misbehave (follow symlinks,
    miss MANIFEST entries, package-data globs). This subcommand opens each
    archive in dist/ and rejects members whose path begins with `persona/` or
    contains `/persona/`.
    """
    dist = paths.root / "dist"
    if not dist.exists():
        print("INFO  no dist/ directory — nothing to inspect")
        return 0

    archives = sorted(
        p for p in dist.iterdir()
        if p.is_file() and (
            p.name.endswith(".whl")
            or p.name.endswith(".tar.gz")
            or p.name.endswith(".tgz")
            or p.name.endswith(".zip")
        )
    )
    if not archives:
        print("INFO  dist/ contains no recognized build artifacts (.whl/.tar.gz)")
        return 0

    issues: list[str] = []
    for archive in archives:
        try:
            members = list(_archive_members(archive))
        except (zipfile.BadZipFile, tarfile.TarError, OSError) as exc:
            issues.append(f"{archive.name}: failed to read archive ({exc})")
            continue
        for member in members:
            # Normalize: remove any leading wheel-internal prefix (e.g. "dotpanel-0.3.0/")
            # so we can match the logical path.
            parts = member.split("/")
            if "persona" in parts:
                issues.append(f"{archive.name}: persona content at member {member!r}")

    if issues:
        for issue in issues:
            print(f"FAIL  {issue}", file=sys.stderr)
        return 2
    print(f"OK  no persona content in {len(archives)} archive(s)")
    return 0


# ---------------------------------------------------------------------------
# Subcommand: uninstall
# ---------------------------------------------------------------------------

def cmd_uninstall(paths: DotpanelPaths, harness: str, include_settings: bool,
                  dry_run: bool, *, launchers: bool = False) -> int:
    targets = ("claude", "codex", "kimi") if harness == "all" else (harness,)
    actions: list[str] = []
    for target in targets:
        home = paths.output_root(target, None)
        # Find banner-marked files to remove
        search_roots = [home] if home.exists() else []
        skills_root = _actual_skills_dir(paths, target)
        if skills_root is not None and skills_root.exists() and skills_root not in search_roots:
            search_roots.append(skills_root)
        for root in search_roots:
            for fp in root.rglob("*"):
                if not fp.is_file():
                    continue
                try:
                    rel = str(fp.relative_to(home))
                except ValueError:
                    rel = str(fp.relative_to(paths.home))
                if _excluded_path(rel, target):
                    continue
                if _is_json(fp.name):
                    if include_settings and is_managed_json(fp, paths.home):
                        actions.append(f"REMOVE-JSON {fp}")
                        if not dry_run:
                            fp.unlink()
                    continue
                if has_dotpanel_banner(fp):
                    actions.append(f"REMOVE {fp}")
                    if not dry_run:
                        fp.unlink()
        # Remove empty skill subdirs
        skills = _actual_skills_dir(paths, target)
        if skills is not None and skills.is_dir():
            for d in sorted(skills.glob("*"), reverse=True):
                if d.is_dir() and not any(d.iterdir()):
                    actions.append(f"RMDIR {d}")
                    if not dry_run:
                        d.rmdir()

    # D5: optional --launchers removes ~/.config/dotpanel/path.sh.
    if launchers:
        path_sh = paths.home / PATH_SH_REL
        if path_sh.exists():
            actions.append(f"REMOVE-LAUNCHERS {path_sh}")
            if not dry_run:
                try:
                    path_sh.unlink()
                except OSError as exc:
                    print(f"WARN  could not remove {path_sh}: {exc}", file=sys.stderr)

    for a in actions:
        print(f"{'WOULD' if dry_run else 'OK'}  {a}")
    if not actions:
        print("OK  no banner-marked files found")
    return 0


# ---------------------------------------------------------------------------
# Argument parser + main
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="dotpanel")
    parser.add_argument("--version", action="version", version=f"dotpanel {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("root", help="print absolute path to dotpanel install root")
    sub.add_parser("doctor", help="verify install, symlink, persona, templates")
    audit_p = sub.add_parser("audit", help="structural invariants for CI/pre-commit")
    audit_p.add_argument(
        "--dist",
        action="store_true",
        help="inspect dist/*.whl and dist/*.tar.gz — FAIL on any persona content",
    )

    init_p = sub.add_parser("init", help="create dotpanel/persona symlink and run doctor")
    init_p.add_argument("--persona-root", type=Path, default=None,
                        help="path to persona directory (default: ~/.dotfiles/persona/; "
                             "stub voice.md + identity.yaml seeded if absent)")

    cfg = sub.add_parser("configure", help="render harness adapters")
    cfg.add_argument("--harness", choices=("claude", "codex", "kimi", "all"), required=True)
    cfg.add_argument("--check", action="store_true", help="dry-run validator (no writes)")
    cfg.add_argument("--force", action="store_true", help="overwrite non-banner files (cutover)")
    cfg.add_argument("--dry-run", action="store_true", help="print intended actions, write nothing")
    cfg.add_argument("--output-dir", type=Path, default=None,
                     help=("render to sandbox path instead of ~/.claude / ~/.codex / "
                           "~/.kimi and ~/.agents/skills"))
    # D5: PATH injection knobs.
    cfg.add_argument(
        "--include-substrate-bin", dest="include_substrate_bin",
        action="store_const", const=True, default=None,
        help="force-include substrate tools/bin in ~/.config/dotpanel/path.sh",
    )
    cfg.add_argument(
        "--no-include-substrate-bin", dest="include_substrate_bin",
        action="store_const", const=False,
        help="skip substrate tools/bin in ~/.config/dotpanel/path.sh",
    )
    cfg.add_argument(
        "--inject-shell-rc", action="store_true", default=True,
        dest="inject_shell_rc",
        help="append source line for path.sh to ~/.bashrc and/or ~/.zshrc (idempotent; default: on)",
    )
    cfg.add_argument(
        "--no-inject-shell-rc", action="store_false",
        dest="inject_shell_rc",
        help="skip shell rc injection",
    )
    cfg.add_argument(
        "--prune-orphan-skills", action="store_true",
        help="remove banner-marked skill dirs in ~/.claude/skills/ and ~/.agents/skills/ "
        "whose name is not in the current managed-skills registry (C12)",
    )

    un = sub.add_parser("uninstall", help="remove banner-marked files (preserves runtime data)")
    un.add_argument("--harness", choices=("claude", "codex", "kimi", "all"), required=True)
    un.add_argument("--include-settings", action="store_true",
                    help="also remove DOTPANEL_MANAGED_JSON files (settings.json)")
    un.add_argument("--launchers", action="store_true",
                    help="also remove ~/.config/dotpanel/path.sh (D5)")
    un.add_argument("--dry-run", action="store_true")

    # leaks: pre-push secret-leak guard. IC-4 exit codes 0/2/3.
    leaks_p = sub.add_parser(
        "leaks",
        help="refuse secret/credential files in a git working tree (used by sync)",
    )
    build_leaks_parser(leaks_p)

    # context: identity + machine + paths (was bootstrap).
    context_p = sub.add_parser(
        "context",
        help="emit identity + machine + paths (markdown / --env / --name / --json)",
    )
    build_context_parser(context_p)

    # ssh: machines.yaml → ~/.ssh/config.d/dotpanel.conf (was ssh-gen-config).
    ssh_p = sub.add_parser("ssh", help="render / check / list SSH config from machines.yaml")
    build_ssh_parser(ssh_p)

    # install: pinned external-binary installer (was install-tools).
    install_p = sub.add_parser(
        "install",
        help="install external binaries with SHA-256-verified pins to ~/.local/bin",
    )
    build_install_parser(install_p)

    # secrets: scoped secrets API (was tools/bin/secrets).
    secrets_p = sub.add_parser(
        "secrets",
        help="scoped secrets API (init/list/edit/run/export --scope llm/rotate-key)",
    )
    build_secrets_parser(secrets_p)

    # sync: repo-aware push/pull/diff/status (was tools/bin/dot).
    sync_p = sub.add_parser(
        "sync",
        help="repo sync (push/pull/diff/status/resume/unlock; checkpointed pull)",
    )
    build_sync_parser(sync_p)

    return parser


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    # `secrets` has a `run --key X --backend Y -- cmd args...` shape that
    # argparse cannot model cleanly because the rest of the command line is
    # opaque from argparse's POV. Branch into the secrets dispatcher BEFORE
    # the main argparse pass when we see `secrets`, so the inner module
    # owns the parsing.
    if argv and argv[0] == "secrets":
        from .secrets import main as _secrets_main
        return _secrets_main(argv[1:])

    parser = build_parser()
    args = parser.parse_args(argv)
    paths = DotpanelPaths.default()

    if args.command == "root":
        return cmd_root()
    if args.command == "doctor":
        return cmd_doctor(paths)
    if args.command == "audit":
        if getattr(args, "dist", False):
            return cmd_audit_dist(paths)
        return cmd_audit(paths)
    if args.command == "init":
        return cmd_init(paths, args.persona_root)
    if args.command == "configure":
        return cmd_configure(
            paths, args.harness, args.check, args.force, args.dry_run, args.output_dir,
            include_substrate_bin=args.include_substrate_bin,
            inject_shell_rc_flag=args.inject_shell_rc,
            prune_orphan_skills=args.prune_orphan_skills,
        )
    if args.command == "uninstall":
        return cmd_uninstall(
            paths, args.harness, args.include_settings, args.dry_run,
            launchers=getattr(args, "launchers", False),
        )
    if args.command == "leaks":
        repo = (args.directory or Path.cwd()).resolve()
        return cmd_leaks(repo, args.mode)
    if args.command == "context":
        mode = args.mode_name or args.mode_env or args.mode_json or "markdown"
        return cmd_context(mode)
    if args.command == "ssh":
        return dispatch_ssh(args)
    if args.command == "install":
        return dispatch_install(args)
    if args.command == "secrets":
        return dispatch_secrets(args)
    if args.command == "sync":
        return dispatch_sync(args)
    parser.error(f"unknown command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
