"""dotpanel.ssh — SSH config renderer from substrate machines.yaml.

Reads `infra/machines.yaml` (path resolved via `.dotpanel.toml [paths] infra`)
and renders an SSH config snippet at `~/.ssh/config.d/dotpanel.conf`.

CLI:
    dotpanel ssh render [--output <path>]   # default: ~/.ssh/config.d/dotpanel.conf
    dotpanel ssh check                      # parse machines.yaml; report unknown fields
    dotpanel ssh list [--role <role>]       # tabular host list
    dotpanel ssh help

Naming convention (preserved from v4 ssh-gen-config):
    ssh <name>        — Tailscale MagicDNS (default)
    ssh <name>-pub    — public IP with key
    ssh <name>-jp     — via proxy_jump
    ssh <name>-cf     — Cloudflare tunnel
    ssh <name>-local  — LAN IP

Exit codes (IC-IC-3):
    0  ok
    2  machines.yaml schema error
    3  [paths] infra unset or machines.yaml missing
    4  file write failed
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Any

from .config import find_substrate, SchemaError, SubstrateNotFound


def _load_machines_yaml(path: Path) -> Any:
    try:
        import yaml  # type: ignore[import-not-found]
        return yaml.safe_load(path.read_text(encoding="utf-8"))
    except ImportError:
        # We need full YAML to render SSH config — fail loudly if PyYAML
        # is missing rather than silently emitting a half-rendered file.
        print(
            "FAIL  PyYAML is required for `dotpanel ssh render`. "
            "Install via: pip install pyyaml --break-system-packages",
            file=sys.stderr,
        )
        raise


def _format_host_block(name: str, hostname: str, user: str,
                       port: int = 22, key: str = "", jump: str = "") -> list[str]:
    lines = [f"Host {name}", f"  HostName {hostname}", f"  User {user}"]
    if port != 22:
        lines.append(f"  Port {port}")
    if key:
        lines.append(f"  IdentityFile ~/.ssh/vps-keys/{key}")
    if jump:
        lines.append(f"  ProxyJump {jump}")
    lines.append("")
    return lines


HEADER = [
    "# Auto-generated by dotpanel ssh render",
    "# Do not edit manually — edit infra/machines.yaml instead",
    "",
    "Host *",
    "  ConnectTimeout 10",
    "  ServerAliveInterval 30",
    "  StrictHostKeyChecking accept-new",
    "  ControlMaster auto",
    "  ControlPath ~/.ssh/ctrl-%r@%h:%p",
    "  ControlPersist 7200",
    "",
]


def render_config(data: Any) -> str:
    """Render the SSH config snippet from a parsed machines.yaml dict."""
    lines = list(HEADER)
    servers = (data.get("servers") or []) + (data.get("dev_machines") or [])
    for server in servers:
        if not isinstance(server, dict):
            continue
        name = server.get("name")
        if not name:
            continue
        ip = server.get("ip", "")
        user = server.get("user", "ubuntu")
        key = server.get("ssh_key", "")
        ts_ip = server.get("tailscale_ip", "")
        magicdns = server.get("magicdns", "")
        proxy = server.get("proxy_jump", "")
        aliases = [a.lower() for a in (server.get("alias") or [])]

        if magicdns:
            lines.extend(_format_host_block(name, magicdns, user))
            for alias in aliases:
                lines.extend(_format_host_block(alias, magicdns, user))
        elif ts_ip:
            lines.extend(_format_host_block(name, ts_ip, user))
            for alias in aliases:
                lines.extend(_format_host_block(alias, ts_ip, user))

        if ip:
            lines.extend(_format_host_block(f"{name}-pub", ip, user, key=key))
            for alias in aliases:
                lines.extend(_format_host_block(f"{alias}-pub", ip, user, key=key))
            if proxy:
                lines.extend(_format_host_block(f"{name}-jp", ip, user, key=key, jump=proxy))
                for alias in aliases:
                    lines.extend(_format_host_block(f"{alias}-jp", ip, user, key=key, jump=proxy))

        cf = server.get("cloudflare", {}) or {}
        if cf:
            cf_host = cf.get("hostname", "localhost")
            cf_port = int(cf.get("port", 22))
            lines.extend(_format_host_block(f"{name}-cf", cf_host, user, port=cf_port, key=key))

        lan_ip = server.get("lan_ip", "")
        if lan_ip:
            lines.extend(_format_host_block(f"{name}-local", lan_ip, user))

    return "\n".join(lines)


def _resolve_machines_yaml() -> tuple[Path, Path] | int:
    """Return (machines_yaml, infra_dir) or an exit code on failure."""
    try:
        substrate = find_substrate()
    except SubstrateNotFound as exc:
        print(f"FAIL  {exc}", file=sys.stderr)
        return 2
    if not substrate.has_path("infra"):
        print(
            "FAIL  [paths] infra not set in .dotpanel.toml; cannot render SSH config.",
            file=sys.stderr,
        )
        return 3
    infra_dir = substrate.path_for("infra")
    machines_yaml = infra_dir / "machines.yaml"
    if not machines_yaml.exists():
        print(f"FAIL  machines.yaml not found at {machines_yaml}", file=sys.stderr)
        return 3
    return machines_yaml, infra_dir


def _ensure_include_in_ssh_config(ssh_config: Path) -> bool:
    """Return True if we added the `Include config.d/*` directive."""
    include_line = "Include config.d/*"
    if ssh_config.exists():
        if include_line in ssh_config.read_text(encoding="utf-8"):
            return False
    ssh_config.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if ssh_config.exists() else "w"
    with ssh_config.open(mode, encoding="utf-8") as fh:
        if ssh_config.exists() and ssh_config.stat().st_size > 0:
            fh.write("\n")
        fh.write(include_line + "\n")
    return True


def cmd_ssh_render(output: Path | None = None) -> int:
    resolution = _resolve_machines_yaml()
    if isinstance(resolution, int):
        return resolution
    machines_yaml, _ = resolution
    try:
        data = _load_machines_yaml(machines_yaml)
    except ImportError:
        return 4
    except Exception as exc:  # noqa: BLE001
        print(f"FAIL  machines.yaml parse error: {exc}", file=sys.stderr)
        return 2

    content = render_config(data or {})

    if output is None:
        out_dir = Path.home() / ".ssh" / "config.d"
        out_dir.mkdir(parents=True, mode=0o700, exist_ok=True)
        try:
            out_dir.chmod(0o700)
        except OSError:
            pass
        output = out_dir / "dotpanel.conf"

    try:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8")
        try:
            output.chmod(0o600)
        except OSError:
            pass
    except OSError as exc:
        print(f"FAIL  could not write {output}: {exc}", file=sys.stderr)
        return 4

    # Ensure the include directive exists in ~/.ssh/config (only if writing
    # to the default location; explicit --output is operator-managed).
    if output.parent == Path.home() / ".ssh" / "config.d":
        ssh_config = Path.home() / ".ssh" / "config"
        added = _ensure_include_in_ssh_config(ssh_config)
        if added:
            print(f"OK  added 'Include config.d/*' to {ssh_config}")

    print(f"OK  wrote {output}")
    return 0


def cmd_ssh_check() -> int:
    resolution = _resolve_machines_yaml()
    if isinstance(resolution, int):
        return resolution
    machines_yaml, _ = resolution
    try:
        data = _load_machines_yaml(machines_yaml) or {}
    except ImportError:
        return 4
    except Exception as exc:  # noqa: BLE001
        print(f"FAIL  machines.yaml parse error: {exc}", file=sys.stderr)
        return 2
    known_fields = {
        "name", "alias", "ip", "user", "ssh_key", "tailscale_ip", "magicdns",
        "proxy_jump", "cloudflare", "lan_ip", "os", "spec", "role", "person",
        "provider", "tags", "notes",
    }
    issues: list[str] = []
    for group in ("servers", "dev_machines"):
        for server in data.get(group, []) or []:
            if not isinstance(server, dict):
                continue
            name = server.get("name", "<unknown>")
            for field_name in server:
                if field_name not in known_fields:
                    issues.append(f"{group}/{name}: unknown field '{field_name}'")
    for issue in issues:
        print(f"WARN  {issue}")
    print(f"OK  machines.yaml parsed ({len(data.get('servers') or []) + len(data.get('dev_machines') or [])} hosts)")
    return 0


def cmd_ssh_list(role: str | None = None) -> int:
    resolution = _resolve_machines_yaml()
    if isinstance(resolution, int):
        return resolution
    machines_yaml, _ = resolution
    try:
        data = _load_machines_yaml(machines_yaml) or {}
    except ImportError:
        return 4
    except Exception as exc:  # noqa: BLE001
        print(f"FAIL  machines.yaml parse error: {exc}", file=sys.stderr)
        return 2

    rows: list[tuple[str, str, str, str]] = []
    for group in ("servers", "dev_machines"):
        for server in data.get(group, []) or []:
            if not isinstance(server, dict):
                continue
            if role and server.get("role") != role:
                continue
            rows.append((
                str(server.get("name", "")),
                str(server.get("role", "")),
                str(server.get("os", "")),
                str(server.get("ip") or server.get("tailscale_ip") or ""),
            ))
    if not rows:
        print("INFO  no hosts match the filter")
        return 0
    name_w = max(len(r[0]) for r in rows) + 2
    role_w = max(len(r[1]) for r in rows) + 2
    os_w = max(len(r[2]) for r in rows) + 2
    for name, role_, os_, addr in rows:
        print(f"{name:<{name_w}}{role_:<{role_w}}{os_:<{os_w}}{addr}")
    return 0


def build_ssh_parser(parser: argparse.ArgumentParser) -> None:
    sub = parser.add_subparsers(dest="ssh_action", required=True)
    render_p = sub.add_parser("render", help="render machines.yaml → ~/.ssh/config.d/dotpanel.conf")
    render_p.add_argument("--output", type=Path, default=None,
                          help="write to a custom path instead of the default")
    sub.add_parser("check", help="parse machines.yaml + report unknown fields")
    list_p = sub.add_parser("list", help="tabular host list")
    list_p.add_argument("--role", default=None, help="filter by role")
    sub.add_parser("help", help="show this help")


def dispatch_ssh(args: argparse.Namespace) -> int:
    action = args.ssh_action
    if action == "render":
        return cmd_ssh_render(args.output)
    if action == "check":
        return cmd_ssh_check()
    if action == "list":
        return cmd_ssh_list(args.role)
    if action == "help":
        print(__doc__ or "")
        return 0
    return 2


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="dotpanel ssh")
    build_ssh_parser(parser)
    args = parser.parse_args(argv)
    return dispatch_ssh(args)


if __name__ == "__main__":
    raise SystemExit(main())
