#!/usr/bin/env python3
# Generated by dotpanel; do not edit directly.
# Source: harness/claude/templates/statusline.py
# Update: dotpanel configure --harness claude
"""Statusline for Claude Code: git status + context bar (proxy-only)."""

import json
import os
import subprocess
import sys
import time

HOME = os.path.expanduser("~")
CACHE_FILE = os.path.join(HOME, ".claude", "statusline-cache.json")

# Actual model context window sizes (not necessarily what Claude Code reports)
KIMI_WINDOW = 262144          # Kimi moonshot actual window
MINIMAX_WINDOW = 200000       # MiniMax actual window
DEEPSEEK_WINDOW = 1000000     # DeepSeek actual window
CLAUDE_WINDOW = 1000000       # Claude fallback (only used when context_window data is missing)


RED = "\033[31m"
YELLOW = "\033[33m"
GREEN = "\033[38;2;16;183;141m"
MAGENTA = "\033[38;2;240;171;252m"
LIGHT_BLUE = "\033[38;2;135;206;250m"
DIM = "\033[2m"
RESET = "\033[0m"


def bar(pct: int, width: int = 10) -> str:
    filled = (pct * width + 50) // 100
    filled = max(0, min(filled, width))
    return "█" * filled + "░" * (width - filled)


def fmt_resets_in(resets_at) -> str:
    try:
        delta = int(resets_at) - int(time.time())
    except (TypeError, ValueError):
        return ""
    if delta <= 0:
        return ""
    if delta < 3600:
        return f"{max(1, delta // 60)}m"
    if delta < 86400:
        return f"{delta // 3600}h"
    return f"{delta // 86400}d"


def colored_bar(pct: int, width: int = 10) -> str:
    b = bar(pct, width)
    if pct >= 85:
        color = RED
    elif pct >= 70:
        color = YELLOW
    else:
        color = GREEN
    return f"{color}{b}{RESET}"


def git_info(cwd: str):
    if not cwd or not os.path.isdir(os.path.join(cwd, ".git")):
        return "", ""

    try:
        branch = (
            subprocess.check_output(
                ["git", "-C", cwd, "rev-parse", "--abbrev-ref", "HEAD"],
                stderr=subprocess.DEVNULL,
            )
            .decode("utf-8", "ignore")
            .strip()
        )
    except subprocess.CalledProcessError:
        return "", ""

    if not branch:
        return "", ""

    staged = unstaged = untracked = deleted = renamed = conflict = 0
    try:
        porcelain = (
            subprocess.check_output(
                ["git", "-C", cwd, "status", "--porcelain"],
                stderr=subprocess.DEVNULL,
            )
            .decode("utf-8", "ignore")
            .splitlines()
        )
    except subprocess.CalledProcessError:
        porcelain = []

    for line in porcelain:
        if not line:
            continue
        x = line[0] if len(line) > 0 else " "
        y = line[1] if len(line) > 1 else " "

        if x in "MA":
            staged += 1
        elif x == "D":
            deleted += 1
        elif x == "R":
            renamed += 1
        elif x == "U":
            conflict += 1

        if y in "MA":
            unstaged += 1
        elif y == "D":
            deleted += 1
        elif y == "R":
            renamed += 1
        elif y == "U":
            conflict += 1
        elif y == "?":
            untracked += 1

    parts = []
    if conflict:
        parts.append(f"✕{conflict}")
    if staged:
        parts.append(f"+{staged}")
    if unstaged:
        parts.append(f"~{unstaged}")
    if deleted:
        parts.append(f"-{deleted}")
    if renamed:
        parts.append(f"→{renamed}")
    if untracked:
        parts.append(f"?{untracked}")

    git_status = " ".join(parts)
    return branch, git_status


def _load_cache():
    try:
        with open(CACHE_FILE) as f:
            return json.load(f)
    except Exception:
        return {}


def _save_cache(cache):
    try:
        with open(CACHE_FILE, "w") as f:
            json.dump(cache, f)
    except Exception:
        pass


def per_session_usage(transcript_path: str, session_id: str):
    """Scan transcript for per-session cumulative token usage.

    Returns (input_tokens, output_tokens).
    """
    if not transcript_path or not os.path.isfile(transcript_path):
        return 0, 0

    cache = _load_cache()
    cache_key = f"usage:{session_id}"
    cached = cache.get(cache_key, {})

    try:
        current_size = os.path.getsize(transcript_path)
    except Exception:
        return cached.get("input", 0), cached.get("output", 0)

    if cached.get("size") == current_size and "input" in cached and "output" in cached:
        return cached["input"], cached["output"]

    start_size = cached.get("size", 0)
    input_total = cached.get("input", 0)
    output_total = cached.get("output", 0)

    try:
        with open(transcript_path, "rb") as f:
            if start_size > 0:
                f.seek(start_size - 1)
                if f.read(1) == b"\n":
                    f.seek(start_size)
                else:
                    f.seek(start_size)
                    f.readline()
            for line in f:
                try:
                    data = json.loads(line)
                except Exception:
                    continue
                msg = data.get("message", {})
                if msg.get("role") != "assistant":
                    continue
                usage = msg.get("usage", {})
                if not usage:
                    continue
                input_total += usage.get("input_tokens", 0)
                output_total += usage.get("output_tokens", 0)
    except Exception:
        pass

    cache[cache_key] = {"size": current_size, "input": input_total, "output": output_total}
    _save_cache(cache)
    return input_total, output_total


def main():
    data = json.load(sys.stdin)

    ctx_pct = int((data.get("context_window") or {}).get("used_percentage", 0))
    has_ctx_window = data.get("context_window") is not None
    cwd = data.get("cwd") or ""
    session_id = data.get("session_id") or ""
    transcript_path = data.get("transcript_path") or ""

    folder_name = os.path.basename(cwd) if cwd else ""
    branch, git_status = git_info(cwd)

    if folder_name and branch:
        if git_status:
            prefix = f"[{folder_name}]({branch} {git_status})"
        else:
            prefix = f"[{folder_name}]({branch})"
    elif folder_name:
        prefix = f"[{folder_name}]"
    else:
        prefix = ""

    # Detect backend and select the correct context window
    base_url = os.environ.get("ANTHROPIC_BASE_URL", "")
    if "kimi.com" in base_url:
        window = KIMI_WINDOW
    elif "minimaxi" in base_url:
        window = MINIMAX_WINDOW
    elif "deepseek" in base_url:
        window = DEEPSEEK_WINDOW
    else:
        window = CLAUDE_WINDOW

    # Proxy backends may have a smaller reported window than the actual model window.
    # We rescale the percentage so the bar reflects real model capacity.
    # Native Claude is left as-is because Claude Code reports its own window accurately.
    is_proxy = "kimi.com" in base_url or "minimaxi" in base_url or "deepseek" in base_url

    if has_ctx_window:
        cw = data.get("context_window") or {}
        used_tokens = cw.get("used_tokens")
        # Claude Code's idea of the window size (e.g. 200k for Kimi proxy)
        reported_total = cw.get("context_window_size") or cw.get("total_tokens") or cw.get("max_tokens")

        if used_tokens is not None and window > 0:
            # Exact token count available: compute against actual model window
            ctx_pct = (used_tokens * 100 + window // 2) // window
        elif is_proxy and reported_total and reported_total != window and window > 0:
            # Only rescale for proxies. Formula: pct * reported_window / actual_window
            ctx_pct = (ctx_pct * reported_total + window // 2) // window
        # else: native Claude → trust used_percentage from Claude Code

        ctx_pct = min(ctx_pct, 100)
    else:
        # No context_window data: estimate from transcript token usage
        input_tokens, output_tokens = per_session_usage(transcript_path, session_id)
        total = input_tokens + output_tokens
        ctx_pct = (total * 100 + window // 2) // window
        ctx_pct = min(ctx_pct, 100)

    # Detect backend
    backend_tag = ""
    if "kimi.com" in base_url:
        backend_tag = f"{MAGENTA}[KIMI]{RESET}"
    elif "minimaxi" in base_url:
        backend_tag = f"{MAGENTA}[MiniMax]{RESET}"
    elif "deepseek" in base_url:
        backend_tag = f"{MAGENTA}[DS]{RESET}"

    parts = []
    if backend_tag:
        parts.append(backend_tag)
    if prefix:
        parts.append(prefix)
    parts.append(f"Ctx:{colored_bar(ctx_pct)} {ctx_pct}%")

    # Rate-limit bars (Claude.ai subscribers only; absent on proxies / before first response)
    rate_limit_parts = []
    rate_limits = data.get("rate_limits") or {}
    for label, key in (("5h", "five_hour"), ("7d", "seven_day")):
        window_data = rate_limits.get(key)
        if not window_data:
            continue
        pct_raw = window_data.get("used_percentage")
        if pct_raw is None:
            continue
        pct = max(0, min(int(round(float(pct_raw))), 100))
        resets_in = fmt_resets_in(window_data.get("resets_at"))
        suffix = f" {DIM}· resets {resets_in}{RESET}" if resets_in else ""
        rate_limit_parts.append(f"{DIM}{label}:{RESET}{LIGHT_BLUE}{bar(pct, 10)}{RESET} {pct}%{suffix}")

    output = " ".join(parts)
    if rate_limit_parts:
        output += "\n" + " ".join(rate_limit_parts)
    print(output)


if __name__ == "__main__":
    main()
